// @generated by wingfoil::codegen — do not edit.
//
// Produced by running a wiring function and walking the graph it built, so
// every config here is frozen at generation time. Regenerate rather than
// editing: a hand edit is lost on the next run.
//
// Nothing detects at *runtime* that this file is stale. Guard it with a test
// that calls `codegen::check_artifact` — see that function's docs.

wingfoil::nitro! {
    fn desk_generated(g: &GraphBuilder) -> Stream<f64> {
        let n0_ticker = g.ticker(::core::time::Duration::new(0u64, 1000000u32));
        let n1_count = n0_ticker.count();
        let n2_map = n1_count.map({ let size = 50u64; move |n: &u64| (n * size) as f64 });
        let n3_map = n2_map.map({ let fee = 0.25f64; move |notional: &f64| notional - fee });
        let n4_ticker = g.ticker(::core::time::Duration::new(0u64, 4000000u32));
        let n5_count = n4_ticker.count();
        let n6_map = n5_count.map({ let size = 20u64; move |n: &u64| (n * size) as f64 });
        let n7_map = n6_map.map({ let fee = 1.75f64; move |notional: &f64| notional - fee });
        let n8_join = n3_map.join(&n7_map, |x: &f64, y: &f64| x + y);
        n8_join
    }
}
