// @generated by wingfoil::codegen — do not edit.
//
// Produced by running a wiring function and walking the graph it built, so
// every config here is frozen at generation time. Regenerate rather than
// editing: a hand edit is lost on the next run.
//
// Nothing detects at *runtime* that this file is stale. Guard it with a test
// that calls `codegen::check_artifact` — see that function's docs.

wingfoil::nitro! {
    fn desk_generated(g: &GraphBuilder) -> Stream<f64> {
        let n0 = g.ticker(::core::time::Duration::new(0u64, 1000000u32));
        let n1 = n0.count();
        let n2 = n1.map({ let size = 50u64; move |n: &u64| (n * size) as f64 });
        let n3 = n2.map({ let fee = 0.25f64; move |notional: &f64| notional - fee });
        let n4 = g.ticker(::core::time::Duration::new(0u64, 4000000u32));
        let n5 = n4.count();
        let n6 = n5.map({ let size = 20u64; move |n: &u64| (n * size) as f64 });
        let n7 = n6.map({ let fee = 1.75f64; move |notional: &f64| notional - fee });
        let n8 = n3.join(&n7, |x: &f64, y: &f64| x + y);
        n8
    }
}
