// @generated by wingfoil::codegen — do not edit.
//
// Produced by running a wiring function and walking the graph it built, so
// every config here is frozen at generation time. Regenerate rather than
// editing: a hand edit is lost on the next run.
//
// Nothing detects at *runtime* that this file is stale. Guard it with a test
// that calls `codegen::check_artifact` — see that function's docs.

wingfoil::nitro! {
    fn ingest_generated(g: &GraphBuilder) -> Stream<f64> {
        let n0_poll = g.poll({ let venue = 7u64; move || venue_feed(venue) });
        let n1_map = n0_poll.map({ let scale = 0.5f64; move |raw: &u64| *raw as f64 * scale });
        let n2_poll = g.poll({ let venue = 11u64; move || venue_feed(venue) });
        let n3_map = n2_poll.map({ let scale = 2.0f64; move |raw: &u64| *raw as f64 * scale });
        let n4_join = n1_map.join(&n3_map, |x: &f64, y: &f64| x + y);
        n4_join
    }
}
