//! Runs the same graph two ways — the interpreted engine and the
//! build-generated static runner — and checks they agree.
//!
//! The runner lives in `$OUT_DIR/graph.rs` and is (re)generated by `build.rs`
//! from `src/wiring.rs` on every build where the wiring changed; nothing
//! generated is checked in, and the schedule can never go stale.

mod wiring;

mod generated {
    include!(concat!(env!("OUT_DIR"), "/graph.rs"));
}

use wingfoil::*;

fn main() -> anyhow::Result<()> {
    let run_mode = RunMode::HistoricalFrom(NanoTime::ZERO);
    let run_for = RunFor::Cycles(12);

    let (roots, values) = wiring::wire();
    Graph::new(roots, run_mode, run_for).run()?;
    let interpreted = values.peek_value();

    let (roots, values) = wiring::wire();
    generated::run(roots, run_mode, run_for)?;
    let compiled = values.peek_value();

    anyhow::ensure!(
        interpreted == compiled,
        "interpreted and generated runners disagree"
    );
    println!(
        "interpreted engine and build-generated static runner agree on {} values:",
        compiled.len()
    );
    for value in &compiled {
        println!("  {value}");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn build_generated_runner_matches_interpreted_engine() {
        let run_mode = RunMode::HistoricalFrom(NanoTime::ZERO);
        let run_for = RunFor::Cycles(12);

        let (roots, values) = wiring::wire();
        Graph::new(roots, run_mode, run_for).run().unwrap();
        let expected = values.peek_value();
        assert!(!expected.is_empty());

        let (roots, values) = wiring::wire();
        generated::run(roots, run_mode, run_for).unwrap();
        assert_eq!(expected, values.peek_value());
    }
}
