# .readthedocs.yaml
version: 2

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Python environment setup
python:
  install:
    - method: pip
      path: .  wingfoil-python 
    - requirements: wingfoil-python/docs/requirements.txt

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Optionally specify the docs folder and branch
formats:
  - html
  - pdf
