//! **Generic-fallback proof**: ops with **no `OpKind` table row** flowing
//! through `nitro!`'s three expansions — `interpreted()`, fully-monomorphized
//! `compiled()`, and `nested()` islands.
//!
//! The load-bearing trick under test: the macro sees only a method-name
//! *token* (`.delta()`), so it can never name the op's concrete type. Instead
//! it emits calls to naming-convention forwarder functions
//! (`__wf_op_delta_cycle` …) whose generic signatures let **rustc's type
//! inference** resolve the op type from the argument types at the expansion
//! site — including a state local declared as a bare `Default::default()`
//! whose type only exists as the associated projection `<Delta<T> as
//! Op>::State`. LLVM then monomorphizes the call exactly like a hand-written
//! table row.
//!
//! Five op shapes are exercised, all defined *in this test crate* (i.e. from
//! the library's point of view: user code):
//!
//! - [`Scale`] — plain config (`Cfg = f64`), no state;
//! - [`Delta<T>`] — **generic** op with inferred state (`State = Option<T>`);
//! - [`Apply<F>`] — **closure config** (`Cfg = F`), via the `_cycle_owned`
//!   forwarder (the same inference-deferral trick as `cycle_owned_cfg`);
//! - [`Spread`] — **two inputs**, no config: `.spread(&other)`. The `&other`
//!   argument is classified as a stream *edge* at expansion time (it names a
//!   stream bound in the graph), so the fallback wires `In = (&recv, &other)`
//!   — the `join` shape, both edges active;
//! - [`Blend<A, B, C, F>`] — **two inputs + closure config**
//!   (`.blend(&other, |a, b| ..)`) — the user-defined-join shape, generic
//!   in both input types and the closure. It was called `combine` until the
//!   catalog gained a built-in op of that name: forwarder dispatch resolves
//!   `__wf_op_<name>_*` unqualified at the call site, so an out-of-crate op
//!   sharing a name with a built-in is ambiguous rather than shadowing. That
//!   is the cost of the naming convention, and the reason to pick op names
//!   that read as your own;
//!
//! plus in-crate [`Distinct`](wingfoil::ops) — which has `#[op]` but **no
//! table row**, proving the whole `#[op]` catalog reaches `nitro!` through the
//! fallback with zero per-op macro edits; and, at the end of the file, the
//! two formerly-"exotic" shapes as user ops — [`Snap`] (passive data edge,
//! sample's shape) and [`Ratchet`] (seeded accumulator, fold's shape).
//!
//! # It is also the **out-of-crate `#[op]` proof** (#782)
//!
//! An integration test is a separate crate: `crate::` here means *this* crate,
//! not `wingfoil`. So every `#[op]` expansion below is a genuine out-of-crate
//! one, and none of it compiled before #782 — the attribute emitted
//! `impl crate::interp::Builder`, which does not exist here. This file used to
//! hand-write ~40 lines of forwarders, consts and interpreted wiring per op
//! for exactly that reason; all of it is now generated by the same attribute
//! the built-in catalog uses, which is the claim the no-table design makes.
//!
//! [`Ratchet`] alone keeps its hand-written forwarders, and on purpose — see
//! the comment above it.

use std::time::Duration;

use wingfoil::anyhow::Result;
use wingfoil::op;
use wingfoil::op::{Activation, Ctx, Op, Tick};
use wingfoil::prelude::*;
use wingfoil::{NanoTime, RunFor, RunMode};

const HISTORICAL: RunMode = RunMode::HistoricalFrom(NanoTime::ZERO);
const PERIOD: Duration = Duration::from_millis(1);

// ---------------------------------------------------------------------------
// The user ops: ordinary `Op` impls, exactly as they'd appear in an app crate.
// ---------------------------------------------------------------------------

/// Multiply each value by a constant factor. `Cfg = f64`, stateless.
pub struct Scale;

#[op(build = scale)]
impl Op for Scale {
    type Cfg = f64;
    type State = ();
    type In<'a> = (&'a f64,);
    type Out = f64;
    const ACTIVATION: Activation = Activation::NONE;

    fn cycle(
        cfg: &mut f64,
        _state: &mut (),
        input: (&f64,),
        _ctx: &mut Ctx<'_>,
    ) -> Result<Tick<f64>> {
        Ok(Tick::Value(input.0 * *cfg))
    }
}

/// Successive difference — a **generic** user op: `State = Option<T>` must be
/// inferred through the forwarder call (the macro never writes the type).
pub struct Delta<T>(std::marker::PhantomData<T>);

#[op(build = delta)]
impl<T> Op for Delta<T>
where
    T: Clone + std::ops::Sub<Output = T> + 'static,
{
    type Cfg = ();
    type State = Option<T>;
    type In<'a> = (&'a T,);
    type Out = T;
    const ACTIVATION: Activation = Activation::NONE;

    fn cycle(
        _cfg: &mut (),
        state: &mut Option<T>,
        input: (&T,),
        _ctx: &mut Ctx<'_>,
    ) -> Result<Tick<T>> {
        let curr = input.0.clone();
        let out = match state.take() {
            Some(prev) => Tick::Value(curr.clone() - prev),
            None => Tick::Quiet,
        };
        *state = Some(curr);
        Ok(out)
    }
}

/// Apply a closure — the op whose **config is the closure** (`Cfg = F`), like
/// the built-in map. Exercises the `_cycle_owned` literal-closure path.
pub struct Apply<F>(std::marker::PhantomData<F>);

#[op(build = apply)]
impl<F> Op for Apply<F>
where
    F: Fn(&f64) -> f64 + 'static,
{
    type Cfg = F;
    type State = ();
    type In<'a> = (&'a f64,);
    type Out = f64;
    const ACTIVATION: Activation = Activation::NONE;

    fn cycle(
        cfg: &mut F,
        _state: &mut (),
        input: (&f64,),
        _ctx: &mut Ctx<'_>,
    ) -> Result<Tick<f64>> {
        Ok(Tick::Value(cfg(input.0)))
    }
}

/// Difference of two streams: `a − b`. Two active inputs, no config, no
/// state — the minimal multi-input op.
pub struct Spread;

#[op(build = spread)]
impl Op for Spread {
    type Cfg = ();
    type State = ();
    type In<'a> = (&'a f64, &'a f64);
    type Out = f64;
    const ACTIVATION: Activation = Activation::NONE;

    fn cycle(
        _cfg: &mut (),
        _state: &mut (),
        input: (&f64, &f64),
        _ctx: &mut Ctx<'_>,
    ) -> Result<Tick<f64>> {
        Ok(Tick::Value(input.0 - input.1))
    }
}

/// A user-defined `join`: fold two streams together with a closure — generic in
/// both input types, the output, and the closure. The primary custom-op use
/// case: multiple inputs *and* a closure config, all resolved by inference.
pub struct Blend<A, B, C, F>(std::marker::PhantomData<(A, B, C, F)>);

#[op(build = blend)]
impl<A, B, C, F> Op for Blend<A, B, C, F>
where
    A: 'static,
    B: 'static,
    C: Clone + 'static,
    F: Fn(&A, &B) -> C + 'static,
{
    type Cfg = F;
    type State = ();
    type In<'a> = (&'a A, &'a B);
    type Out = C;
    const ACTIVATION: Activation = Activation::NONE;

    fn cycle(cfg: &mut F, _state: &mut (), input: (&A, &B), _ctx: &mut Ctx<'_>) -> Result<Tick<C>> {
        Ok(Tick::Value(cfg(input.0, input.1)))
    }
}

// ---------------------------------------------------------------------------
// The fluent methods, so `wire()`/`interpreted()` see the same vocabulary.
//
// Nothing else is written by hand. `#[op(build = <name>)]` on each impl above
// generates, in this crate, exactly what it generates inside `wingfoil`:
//
//   * the `__WF_OP_<NAME>_{ACTIVATION,PASSIVE}` consts and the
//     `__wf_op_<name>_{cycle,cycle_owned,start,start_owned,stop,teardown,
//     seed_state,seed_value}` forwarders that `nitro!`'s `compiled()` /
//     `nested()` emission resolves by naming convention — the ~40 lines per op
//     this file hand-wrote until #782;
//   * the interpreted wiring, as a per-op extension trait
//     (`__WfBuildScale` … `__WfBuildSnap`) implemented for
//     `wingfoil::interp::Builder`. It is in scope below because these ops are
//     declared in this file; from another module it takes a `use`.
//
// So the whole cost of a user op is now `impl Op` + the attribute + the fluent
// method below.
// ---------------------------------------------------------------------------

trait CustomOps {
    fn scale(&self, factor: f64) -> Stream<f64>;
    fn delta(&self) -> Stream<f64>;
    fn apply<F: Fn(&f64) -> f64 + 'static>(&self, f: F) -> Stream<f64>;
    fn spread(&self, other: &Stream<f64>) -> Stream<f64>;
    fn blend<F: Fn(&f64, &f64) -> f64 + 'static>(&self, other: &Stream<f64>, f: F) -> Stream<f64>;
}

impl CustomOps for Stream<f64> {
    fn scale(&self, factor: f64) -> Stream<f64> {
        self.wire(move |b, h| b.scale(h, factor))
    }

    fn delta(&self) -> Stream<f64> {
        self.wire(|b, h| b.delta(h))
    }

    fn apply<F: Fn(&f64) -> f64 + 'static>(&self, f: F) -> Stream<f64> {
        self.wire(move |b, h| b.apply(h, f))
    }

    fn spread(&self, other: &Stream<f64>) -> Stream<f64> {
        let other = other.handle();
        self.wire(move |b, h| b.spread(h, other))
    }

    fn blend<F: Fn(&f64, &f64) -> f64 + 'static>(&self, other: &Stream<f64>, f: F) -> Stream<f64> {
        let other = other.handle();
        self.wire(move |b, h| b.blend(h, other, f))
    }
}

// ---------------------------------------------------------------------------
// The graphs: custom ops chained with built-ins, no `OpKind` rows anywhere.
// ---------------------------------------------------------------------------

wingfoil::nitro! {
    fn custom_ops_graph(g: &GraphBuilder) -> (Stream<f64>, Stream<u64>) {
        let squares = g.ticker(PERIOD).count().map(|c| (c * c) as f64);
        let smoothed = squares.scale(0.5).delta().apply(|x| x + 1.0);
        let levels = g.ticker(PERIOD).count().map(|c| c / 3).distinct();
        (smoothed, levels)
    }
}

/// All three engines agree, and the values match a hand computation:
/// `0.5·c²` deltas are `c − 0.5` (quiet at c=1), `+1` → `c + 0.5`; at c=8
/// that is `8.5`. `c/3` for c=1..8 is 0,0,0,1,1,1,2,2 → distinct ends at 2.
#[test]
fn custom_ops_compiled_matches_interpreted() {
    let run_for = RunFor::Cycles(8);

    let (mut runner, smoothed, levels) = custom_ops_graph::interpreted();
    runner.run(HISTORICAL, run_for).unwrap();
    let (smoothed_i, levels_i) = (runner.value(smoothed), runner.value(levels));
    assert_eq!(8.5, smoothed_i);
    assert_eq!(2, levels_i);

    let (smoothed_c, levels_c) = custom_ops_graph::compiled(HISTORICAL, run_for).unwrap();
    assert_eq!(smoothed_i, smoothed_c);
    assert_eq!(levels_i, levels_c);
}

wingfoil::nitro! {
    fn scaled_delta(g: &GraphBuilder, src: &Stream<f64>) -> Stream<f64> {
        let out = src.scale(2.0).delta();
        out
    }
}

/// Custom ops inside a compiled **island**: the input-taking graph mounts as
/// one node in an interpreted outer graph; its interior is the same
/// forwarder-monomorphized code `compiled()` emits. `2c²` deltas are
/// `2(2c−1) = 4c−2`; at c=6 that is `22`.
#[test]
fn custom_ops_in_nested_island() {
    let g = GraphBuilder::new();
    let src = g.ticker(PERIOD).count().map(|c| (c * c) as f64);
    let island = scaled_delta::nested(&g, &src);
    let out = island.handle();
    let mut runner = g.build();
    runner.run(HISTORICAL, RunFor::Cycles(6)).unwrap();
    assert_eq!(22.0, runner.value(out));
}

wingfoil::nitro! {
    fn multi_input_graph(g: &GraphBuilder) -> (Stream<f64>, Stream<f64>) {
        let fast = g.ticker(PERIOD).count().map(|c| *c as f64);
        let slow = fast.scale(0.5);
        let spread = fast.spread(&slow);
        let combo = fast.blend(&slow, |a: &f64, b: &f64| a + 10.0 * b);
        (spread, combo)
    }
}

/// **Multi-input custom ops** through the fallback: `&slow` is recognised as
/// a stream edge (it names a bound stream), the closure as config. At cycle
/// c: `fast = c`, `slow = c/2`, so `spread = c/2` and
/// `combo = c + 10·(c/2) = 6c`; at c = 8 that is `4` and `48`.
#[test]
fn multi_input_custom_ops_compiled_matches_interpreted() {
    let run_for = RunFor::Cycles(8);

    let (mut runner, spread, combo) = multi_input_graph::interpreted();
    runner.run(HISTORICAL, run_for).unwrap();
    let (spread_i, combo_i) = (runner.value(spread), runner.value(combo));
    assert_eq!(4.0, spread_i);
    assert_eq!(48.0, combo_i);

    let (spread_c, combo_c) = multi_input_graph::compiled(HISTORICAL, run_for).unwrap();
    assert_eq!(spread_i, spread_c);
    assert_eq!(combo_i, combo_c);
}

wingfoil::nitro! {
    fn spread_island(g: &GraphBuilder, a: &Stream<f64>, b: &Stream<f64>) -> Stream<f64> {
        let out = a.spread(b);
        out
    }
}

/// A multi-input custom op as the body of a **two-input island**: both outer
/// streams feed the composite, the interior is the monomorphized fallback
/// dispatch. `spread = 3c − c = 2c`; at c = 5 that is `10`.
#[test]
fn multi_input_custom_op_in_nested_island() {
    let g = GraphBuilder::new();
    let count = g.ticker(PERIOD).count();
    let fast = count.map(|c| (3 * *c) as f64);
    let slow = count.map(|c| *c as f64);
    let island = spread_island::nested(&g, &fast, &slow);
    let out = island.handle();
    let mut runner = g.build();
    runner.run(HISTORICAL, RunFor::Cycles(5)).unwrap();
    assert_eq!(10.0, runner.value(out));
}

// ---------------------------------------------------------------------------
// The two formerly-"exotic" shapes, as USER ops — proving they are ordinary:
// a passive-edge op (sample's shape) and a seeded accumulator (fold's shape).
//
// `Snap` is derived: `#[op(build = snap, passive = [0])]` writes its
// forwarders, its passive mask and its interpreted wiring, out-of-crate.
//
// `Ratchet` keeps its forwarders **by hand, deliberately** — it is the file's
// pin on the naming convention the emission resolves against, and the one
// shape the derive's seeding conventions do not express: its state *and* its
// value slot are seeded from `Cfg` (the floor), which is neither `#[op]`'s
// `Default` seed nor `init_arg`'s call-site seed (that one wants a literal
// closure config, which `ratchet` has not got). The hand-written escape hatch
// stays supported for exactly this: an op whose shape is outside the
// conventions writes the ~40 lines and everything else about it is unchanged.
// ---------------------------------------------------------------------------

/// User sample: emit the (passive) data value when the trigger ticks.
pub struct Snap<T>(std::marker::PhantomData<T>);

#[op(build = snap, passive = [0])]
impl<T: Clone + 'static> Op for Snap<T> {
    type Cfg = ();
    type State = ();
    type In<'a> = (&'a T, &'a ());
    type Out = T;
    const ACTIVATION: Activation = Activation::NONE;

    fn cycle(
        _cfg: &mut (),
        _state: &mut (),
        input: (&T, &()),
        _ctx: &mut Ctx<'_>,
    ) -> Result<Tick<T>> {
        Ok(Tick::Value(input.0.clone()))
    }
}

/// User seeded accumulator: running max, seeded with (and floored at) `init`.
pub struct Ratchet;

impl Op for Ratchet {
    /// The floor — also the state/value seed.
    type Cfg = f64;
    type State = f64;
    type In<'a> = (&'a f64,);
    type Out = f64;
    const ACTIVATION: Activation = Activation::NONE;

    fn cycle(
        _cfg: &mut f64,
        state: &mut f64,
        input: (&f64,),
        _ctx: &mut Ctx<'_>,
    ) -> Result<Tick<f64>> {
        *state = state.max(*input.0);
        Ok(Tick::Value(*state))
    }
}

pub const __WF_OP_RATCHET_ACTIVATION: Activation = Ratchet::ACTIVATION;
pub const __WF_OP_RATCHET_PASSIVE: u32 = 0;

pub fn __wf_op_ratchet_cycle(
    cfg: &mut <Ratchet as Op>::Cfg,
    state: &mut <Ratchet as Op>::State,
    input: ((&f64, bool),),
    ctx: &mut Ctx<'_>,
) -> Result<Tick<f64>> {
    <Ratchet as Op>::cycle(cfg, state, (input.0.0,), ctx)
}

pub fn __wf_op_ratchet_start<C, S>(_cfg: &mut C, _state: &mut S, _ctx: &mut Ctx<'_>) -> Result<()> {
    Ok(())
}

/// Seeded shape: the plain argument (the floor) seeds state *and* slot, so a
/// passive read before the first tick sees the floor, not 0.0.
pub fn __wf_op_ratchet_seed_state(cfg: &f64) -> f64 {
    *cfg
}
pub fn __wf_op_ratchet_seed_value(cfg: &f64) -> f64 {
    *cfg
}

pub fn __wf_op_ratchet_stop(
    cfg: &mut <Ratchet as Op>::Cfg,
    state: &mut <Ratchet as Op>::State,
    input: ((&f64, bool),),
    ctx: &mut Ctx<'_>,
) -> Result<()> {
    let _ = input;
    <Ratchet as Op>::stop(cfg, state, ctx)
}
pub fn __wf_op_ratchet_teardown(
    cfg: &mut <Ratchet as Op>::Cfg,
    state: &mut <Ratchet as Op>::State,
    input: ((&f64, bool),),
    ctx: &mut Ctx<'_>,
) -> Result<()> {
    let _ = input;
    <Ratchet as Op>::teardown(cfg, state, ctx)
}

trait ShapeOps {
    fn snap(&self, trigger: &Stream<()>) -> Stream<f64>;
    fn ratchet(&self, floor: f64) -> Stream<f64>;
}

impl ShapeOps for Stream<f64> {
    fn snap(&self, trigger: &Stream<()>) -> Stream<f64> {
        let trigger = trigger.handle();
        // `#[op(passive = [0])]` put the passive mask on the op, so the
        // generated wiring already reads the data edge without being
        // triggered by it — no `bimap` runtime flags needed.
        self.wire(move |b, h| b.snap(h, trigger))
    }

    fn ratchet(&self, floor: f64) -> Stream<f64> {
        // fold is the public interpreted primitive for the seeded shape —
        // identical math, and it seeds the slot with `floor` just like the
        // compiled emission's seed forwarders.
        self.fold(floor, |acc, v| *acc = acc.max(*v))
    }
}

wingfoil::nitro! {
    fn shapes_graph(g: &GraphBuilder) -> (Stream<f64>, Stream<f64>) {
        let data = g.ticker(PERIOD).count().map(|c| *c as f64);
        let trig = g.ticker(Duration::from_millis(3));
        let snapped = data.snap(&trig);
        let peak = data.map(|v| 10.0 - (*v - 4.0).abs()).ratchet(5.0);
        (snapped, peak)
    }
}

/// The passive-edge and seeded shapes as user ops. At cycle times 0..6ms:
/// `data = c` (1..7); the 3ms trigger ticks at t ∈ {0, 3, 6}, so `snapped`
/// last updates at t = 6 with `data = 7`. The tent `10 − |c − 4|` runs
/// 7,8,9,10,9,8,7 and `ratchet(5.0)` holds the max: `10`.
#[test]
fn user_passive_and_seeded_shapes() {
    let run_for = RunFor::Cycles(7);

    let (mut runner, snapped, peak) = shapes_graph::interpreted();
    runner.run(HISTORICAL, run_for).unwrap();
    let (snapped_i, peak_i) = (runner.value(snapped), runner.value(peak));
    assert_eq!(7.0, snapped_i);
    assert_eq!(10.0, peak_i);

    let (snapped_c, peak_c) = shapes_graph::compiled(HISTORICAL, run_for).unwrap();
    assert_eq!(snapped_i, snapped_c);
    assert_eq!(peak_i, peak_c);
}
