//! Op-completeness guard: protection against **one-sided op registration**,
//! adapted to the forwarder dispatch design.
//!
//! The port plan (Phase 1) called for a `supported_ops!()` list that both the
//! `nitro!` parse-match and its "unsupported op" error message consume, plus a
//! test diffing that list against the fluent trait surface. That design is
//! **obsolete**: the `nitro!` op *table* was deleted (see
//! `docs/macro-extensibility-decision.md`) — the macro now dispatches through
//! naming-convention forwarders (`__wf_op_<name>_*`, generated by `#[op]`), so
//! there is no central op list to diff and an unknown op simply fails to
//! resolve a forwarder at expansion time.
//!
//! The guard the plan wanted still holds, realized as a **compile-time** test.
//! A combinator *used inside* a `nitro!` wiring function only compiles if it
//! has **both**:
//!   * a fluent method (the wiring fn is ordinary fluent code — a missing
//!     method is a compile error), **and**
//!   * a `nitro!` forwarder (`#[op]` emits it — a missing one fails to resolve
//!     `__wf_op_<name>_cycle` / `__WF_OP_<NAME>_ACTIVATION` at the call site).
//!
//! So the `nitro!` blocks below *are* the two-sided guard: every dual-mode
//! combinator is exercised here, so dropping either side (fluent method or
//! forwarder) breaks this build. Each block also asserts
//! `interpreted() == compiled()`, extending interpreted-vs-compiled parity
//! across the whole combinator surface — the biggest engine-drift surface in
//! the codebase. (`nested()` island parity is covered separately in
//! `nested_islands.rs`.)
//!
//! ## The fluent-only surface (deliberately excluded from the `nitro!` blocks)
//!
//! These combinators exist fluently (and run on the interpreted engine) but are
//! **not** used in a `nitro!` block above, in three categories. Adding a new op
//! means consciously placing it in a `nitro!` block or in one of these lists —
//! never silently in neither.
//!
//! That rule is only as good as its coverage, and it had a hole: the whole of
//! `StatisticsOps` — 36 methods — was in neither, because the guard was
//! written against `StreamOps` and nobody extended it when the statistics
//! surface landed. All 36 are now classified: 25 dual-mode, exercised in the
//! `surface_stats_*` blocks, and 11 in category 2b below.
//!
//! **1. IO / cycle — not expressible by design** (capability matrix `❌`):
//!   * `external`, `channel`, `poll` — IO / threaded / busy-poll sources; the
//!     compiled path runs its own loop with no external wake.
//!   * `feedback` (source + the `feedback` close method) — a cycle in the DAG,
//!     which straight-line compiled emission cannot express (v1 out-of-scope).
//!   * `for_each` — a fallible IO sink; lives at the runtime boundary.
//!
//! **2. Sugar over a primitive — spell the primitive in `nitro!`:**
//!   * `not` → `map(|b| !b)`; `collapse` → `map_filter`; `split` → two `map`s.
//!     (`map_n` / `fan` / `merge_all` are the *exception* — the macro
//!     recognises them, unrolling the first two as repetition sugar and
//!     emitting the last two through the variadic `merge_n`; covered in
//!     `surface_sugar` below and in `merge_n.rs`.)
//!
//!     `merge_all` was in this list while it *was* sugar (a chain of 2-ary
//!     `merge`s). It is now a real op — `MergeN`, one of the catalog's two
//!     variadic ops — because the chain cost `n - 1` extra nodes and lost to
//!     legacy's single `merge(vec)` on a wide fan-in. Its forwarders are
//!     hand-written (a slice `In` is unparseable by `#[op]`), so the two-sided
//!     guard this file provides matters more for it than for a generated op,
//!     not less: the `nitro!` blocks in `merge_n.rs` are what pin them.
//!
//!     **`combine`** — the other variadic op (`CombineN`), and the other
//!     fan-in — is pinned the same way, by `combine_n.rs`. Worth naming here
//!     because until it reached the compiled tiers it was in *neither* a
//!     `nitro!` block nor any list below: the "silently in neither" state this
//!     file exists to prevent, hiding in the one op whose spelling
//!     (`g.combine(&[..])`, on the builder rather than on a stream) put it
//!     outside the `StreamOps` surface the guard was written against — the
//!     same blind spot that swallowed all 36 of `StatisticsOps`.
//!
//! **2b. Ergonomic fluent signature ≠ the op's `Cfg` — fluent-only:**
//!   * `logged` — the `Logged` op's `Cfg` is `(String, log::Level)`, but the
//!     fluent method takes `&str` and converts (so dynamic `format!` labels
//!     work, matching legacy). `nitro!`/compiled uses the *call-site arg
//!     types* as the `Cfg` verbatim, so the same tokens cannot satisfy both a
//!     `&str` fluent param and a `String` cfg. `#[op(build = logged)]` still
//!     emits forwarders (harmless) and the interpreted `Builder::logged` the
//!     fluent method wires through; it just isn't spelled in a `nitro!` block.
//!     A debug/logging tap has no place in a self-driving compiled kernel
//!     anyway, so this costs nothing real.
//!   * The **11 `time_windowed_*` statistics methods** — `time_windowed_sum`
//!     / `_mean` / `_min` / `_max` / `_var` / `_std` / `_median`, and the
//!     `_mean_time_weighted` / `_var_time_weighted` / `_std_time_weighted` /
//!     `_median_time_weighted` four. Identical mechanism to `logged`: the ops'
//!     `Cfg` is `NanoTime`, the fluent methods take a `Duration` and convert,
//!     and `nitro!` cannot satisfy both with one set of call-site tokens.
//!     Unlike `logged` this *is* a real gap — a time-windowed statistic is
//!     exactly the kind of thing a compiled kernel should carry — and it
//!     closes by moving the conversion into the op (take `Duration` as `Cfg`
//!     and convert in `start`, as `Ticker` does), not by touching the macro.
//!     The other 25 statistics ops are dual-mode and exercised in the three
//!     `surface_stats_*` blocks below.
//!
//! **3. Currently interpreted-only — candidate follow-up, not by design:**
//!   * *(empty — all four former members are now dual-mode.)* `join_passive`,
//!     `try_join_passive`, `delay_with_reset`, and `with_time` were once
//!     interpreted-only for want of a `nitro!` forwarder; they now carry one
//!     (see `surface_passive_delay` below, exercised across all three engines)
//!     and moved out of this list. The mechanism, for each:
//!     - `join_passive` / `try_join_passive` — the passive-edge join shape. A
//!       second `#[op]` cannot attach to `Join` / `TryJoin` (only the passive
//!       mask differs), so a thin forwarder-witness op (`JoinPassive` /
//!       `TryJoinPassive` in `ops.rs`, `#[op(passive = [1])]`, delegating its
//!       `cycle` to `Join` / `TryJoin`) emits the `__wf_op_join_passive_*` /
//!       `__wf_op_try_join_passive_*` forwarders.
//!     - `delay_with_reset` — the real op's `In = (&T, bool, bool)` (two tick
//!       flags, the trigger's value unread) is unparseable by `#[op]`; a
//!       witness op (`DelayWithResetFwd`) restates it in the two-edge
//!       `(&T, bool, &U, bool)` form `#[op]` parses and delegates to
//!       `DelayWithReset::cycle`.
//!     - `with_time` — `#[op(build = with_time, no_builder)]` on the op itself
//!       (the hand-written `Builder::with_time` stays for its `T: Clone`-only
//!       interpreted seeding — it is now the catalog's *only* `no_builder`
//!       op; every other shape gets its `Builder` method generated, and the
//!       `bimap`/`trimap` family are extra hand-written methods over the
//!       `Join`/`Join3` ops, not opt-outs). Inside `nitro!`/compiled the output must be
//!       `Default` (`(NanoTime, T): Default`), which holds for every value type
//!       used here; the differing pre-first-tick seed is never observed because
//!       the op ticks in lockstep with its source.
//!
//! This file is the single place that classification is written down; the
//! *enforcement* is that everything in category (none) — i.e. every op meant to
//! be dual-mode — compiles in a `nitro!` block.

use std::time::Duration;

use wingfoil::ops::EwmaDecay;
use wingfoil::prelude::*;
use wingfoil::stats::StatisticsOps;
use wingfoil::{NanoTime, RunFor, RunMode};

const HISTORICAL: RunMode = RunMode::HistoricalFrom(NanoTime::ZERO);
const P: Duration = Duration::from_millis(10);
const RUN: RunFor = RunFor::Cycles(12);

// The stateless / single-input `u64` surface: `count`, `map`, `map_filter`,
// `distinct`, `drop_small_change`, `difference`, `limit`, `inspect`, `filter`
// (against a derived bool stream), `merge`, and `accumulate`.
wingfoil::nitro! {
    fn surface_u64(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let mapped = count.map(|i| i * 2);
        let filtered = mapped.map_filter(|i| (*i, *i % 4 == 0));
        let distinct = filtered.distinct();
        // Steps of 4 against a threshold of 8: every other value is dropped,
        // so this exercises the suppressed path, not just the pass-through.
        let stable = distinct.drop_small_change(|c: &u64, p: &u64| c.abs_diff(*p) < 8);
        let diff = stable.difference();
        let limited = diff.limit(100);
        let seen = limited.inspect(|_| ());
        let is_even = count.map(|i| i.is_multiple_of(2));
        let evens = count.filter(&is_even);
        let out = seen.merge(&evens).accumulate();
        out
    }
}

// Scheduling / buffering single-input surface: `delay`, `throttle`, `window`,
// `buffer`.
wingfoil::nitro! {
    fn surface_scheduling(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let delayed = count.delay(Duration::from_millis(25));
        let throttled = delayed.throttle(Duration::from_millis(15));
        let out = throttled.accumulate();
        out
    }
}

// Window / buffer (both emit `Vec<u64>` on a boundary).
wingfoil::nitro! {
    fn surface_windowing(g: &GraphBuilder) -> Stream<Vec<Vec<u64>>> {
        let count = g.ticker(P).count();
        let windowed = count.window(Duration::from_millis(30));
        let buffered = count.buffer(3);
        let out = windowed.merge(&buffered).accumulate();
        out
    }
}

// Multi-input active surface: `join` and `merge`.
wingfoil::nitro! {
    fn surface_multi(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let a = count.map(|i| i * 10);
        let b = count.map(|i| i * 100);
        // Param types annotated so inference doesn't explore unrelated blanket
        // `Add` impls (e.g. nalgebra's, pulled in under the `augurs` feature).
        let joined = a.join(&b, |x: &u64, y: &u64| x + y);
        let out = joined.merge(&a).accumulate();
        out
    }
}

// Time / passive-read surface: `ticked_at`, `ticked_at_elapsed`, `sample`.
wingfoil::nitro! {
    fn surface_time(g: &GraphBuilder) -> Stream<Vec<NanoTime>> {
        let count = g.ticker(P).count();
        let at = count.ticked_at();
        let elapsed = count.ticked_at_elapsed();
        let flag = count.map(|i| i.is_multiple_of(2));
        let trigger = count.filter(&flag).map(|_| ());
        let gated = at.sample(&trigger);
        let out = gated.merge(&elapsed).accumulate();
        out
    }
}

// Fallible active surface: `try_map`, `try_join`.
wingfoil::nitro! {
    fn surface_fallible(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let tried = count.try_map(|i| Ok(i + 1));
        let other = count.map(|i| i * 2);
        let joined = tried.try_join(&other, |x: &u64, y: &u64| Ok(x + y));
        let out = joined.accumulate();
        out
    }
}

// Repetition sugar the macro recognises: `map_n`, `fan`.
wingfoil::nitro! {
    fn surface_sugar(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let deep = count.map_n(3, |i| *i + 1);
        let fanned = deep.fan(2, |s| s.map(|i| *i * 2));
        let other = count.map(|i| *i + 100);
        let merged = fanned.merge_all(&[&other]);
        let out = merged.accumulate();
        out
    }
}

// Lifecycle / passthrough surface: `print` (a plain per-tick pass-through
// since deviation D8 dropped its teardown buffer) and `timed` (passes values
// through unchanged while carrying the start/stop hooks the compiled path
// emits).
wingfoil::nitro! {
    fn surface_lifecycle(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let printed = count.print();
        let timed = printed.timed();
        let out = timed.accumulate();
        out
    }
}

// Formerly-interpreted-only surface, now dual-mode: `with_time`,
// `join_passive`, `try_join_passive`, and `delay_with_reset`. Each reaches
// `nitro!`/compiled through a forwarder added alongside its op (see the module
// doc, category 3). Exercising them here — and in the `nested` parity test
// below — is exactly the two-sided guard: a dropped forwarder fails to resolve
// `__wf_op_<name>_cycle` at these call sites.
wingfoil::nitro! {
    fn surface_passive_delay(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        // `with_time`: (NanoTime, u64) folded back to a single u64 stream. The
        // engine clock is deterministic in historical mode, so the stamped time
        // agrees across engines.
        let stamped = count
            .with_time()
            .map(|pair: &(NanoTime, u64)| u64::from(pair.0) + pair.1);
        // Two derived streams to join; `passive_src` is read passively.
        let base = count.map(|i| i * 2);
        let passive_src = count.map(|i| i * 100);
        // `join_passive` / `try_join_passive`: `base` active, `passive_src`
        // read passively (does not activate the node).
        let joined = base.join_passive(&passive_src, |x: &u64, y: &u64| x + y);
        let tried = base.try_join_passive(&passive_src, |x: &u64, y: &u64| Ok(x + y));
        // `delay_with_reset`: delay `count`, snapping to the live value whenever
        // the reset trigger (even counts) ticks.
        let flag = count.map(|i| i.is_multiple_of(2));
        let trigger = count.filter(&flag);
        let delayed = count.delay_with_reset(Duration::from_millis(25), &trigger);
        let out = joined
            .merge(&tried)
            .merge(&delayed)
            .merge(&stamped)
            .accumulate();
        out
    }
}

// --- The statistics surface -------------------------------------------------
//
// `StatisticsOps` was absent from this guard entirely — not in a `nitro!`
// block, not in a fluent-only list — i.e. exactly the "silently in neither"
// state the module doc forbids, for a third of the op catalog. The three
// blocks below put all 25 of its dual-mode ops under the two-sided guard; the
// 11 that are not dual-mode are listed under category 2b in the module doc.
//
// Every value here is `f64`, and the two engines run the same `cycle` code
// over the same inputs in the same order, so the parity assertion is exact
// equality — no epsilon. A drift big enough to need one would be the bug.

// EWMA and the fixed-count rolling window family.
wingfoil::nitro! {
    fn surface_stats_rolling(g: &GraphBuilder) -> Stream<Vec<f64>> {
        let x = g.ticker(P).count().map(|i| *i as f64);
        let ewma = x.ewma(EwmaDecay::PerTick(0.5));
        let per_tick = x.ewma_per_tick(0.5);
        let half_life = x.ewma_half_life(Duration::from_millis(50));
        let sum = x.rolling_sum(3);
        let mean = x.rolling_mean(3);
        let min = x.rolling_min(3);
        let max = x.rolling_max(3);
        let var = x.rolling_var(3);
        let std = x.rolling_std(3);
        let median = x.rolling_median(3);
        let out = ewma
            .merge_all(&[
                &per_tick, &half_life, &sum, &mean, &min, &max, &var, &std, &median,
            ])
            .accumulate();
        out
    }
}

// The cumulative (unbounded-window) family.
wingfoil::nitro! {
    fn surface_stats_cumulative(g: &GraphBuilder) -> Stream<Vec<f64>> {
        let x = g.ticker(P).count().map(|i| *i as f64);
        let sum = x.cumulative_sum();
        let mean = x.cumulative_mean();
        let min = x.cumulative_min();
        let max = x.cumulative_max();
        let var = x.cumulative_var();
        let std = x.cumulative_std();
        let median = x.cumulative_median();
        let out = sum
            .merge_all(&[&mean, &min, &max, &var, &std, &median])
            .accumulate();
        out
    }
}

// The time-weighted family: each weights a sample by how long it stood, so
// these read the engine clock as well as the value. Historical mode makes that
// deterministic, which is what lets the two engines be compared exactly.
wingfoil::nitro! {
    fn surface_stats_time_weighted(g: &GraphBuilder) -> Stream<Vec<f64>> {
        let x = g.ticker(P).count().map(|i| *i as f64);
        let cum_mean = x.cumulative_mean_time_weighted();
        let cum_var = x.cumulative_var_time_weighted();
        let cum_std = x.cumulative_std_time_weighted();
        let cum_median = x.cumulative_median_time_weighted();
        let roll_mean = x.rolling_mean_time_weighted(3);
        let roll_var = x.rolling_var_time_weighted(3);
        let roll_std = x.rolling_std_time_weighted(3);
        let roll_median = x.rolling_median_time_weighted(3);
        let out = cum_mean
            .merge_all(&[
                &cum_var,
                &cum_std,
                &cum_median,
                &roll_mean,
                &roll_var,
                &roll_std,
                &roll_median,
            ])
            .accumulate();
        out
    }
}

// --- Three-engine agreement across the surface ------------------------------
//
// Each block above compiled (proving fluent + forwarder both exist for every op
// it uses); here we also assert the interpreted and compiled engines agree on
// the values, so the completeness guard doubles as combinator-surface parity.

macro_rules! assert_interp_eq_compiled {
    ($m:ident) => {{
        let (mut runner, out) = $m::interpreted();
        runner.run(HISTORICAL, RUN).unwrap();
        let interp = runner.value(out);
        let (compiled,) = $m::compiled(HISTORICAL, RUN).unwrap();
        assert_eq!(
            interp,
            compiled,
            "interpreted vs compiled drift in {}",
            stringify!($m)
        );
        assert!(!interp.is_empty(), "{} produced no values", stringify!($m));
    }};
}

#[test]
fn u64_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_u64);
}

#[test]
fn scheduling_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_scheduling);
}

#[test]
fn windowing_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_windowing);
}

#[test]
fn multi_input_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_multi);
}

#[test]
fn time_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_time);
}

#[test]
fn fallible_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_fallible);
}

#[test]
fn sugar_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_sugar);
}

#[test]
fn lifecycle_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_lifecycle);
}

#[test]
fn passive_delay_surface_interp_eq_compiled() {
    assert_interp_eq_compiled!(surface_passive_delay);
}

/// Full three-engine agreement for the formerly-interpreted-only ops
/// (`with_time`, `join_passive`, `try_join_passive`, `delay_with_reset`):
/// `interpreted() == compiled() == nested()`. The self-contained graph is a
/// source island, so it exposes all three expansions; `nested` mounts it as one
/// node in an interpreted outer graph (following `nested_islands.rs`).
#[test]
fn passive_delay_surface_three_engine_parity() {
    let (mut runner, out) = surface_passive_delay::interpreted();
    runner.run(HISTORICAL, RUN).unwrap();
    let interp = runner.value(out);
    assert!(
        !interp.is_empty(),
        "surface_passive_delay produced no values"
    );

    let (compiled,) = surface_passive_delay::compiled(HISTORICAL, RUN).unwrap();
    assert_eq!(
        interp, compiled,
        "interpreted vs compiled drift in surface_passive_delay"
    );

    let g = GraphBuilder::new();
    let island = surface_passive_delay::nested(&g);
    let mut r = g.build();
    r.run(HISTORICAL, RUN).unwrap();
    assert_eq!(
        interp,
        r.value(&island),
        "interpreted vs nested drift in surface_passive_delay"
    );
}

#[test]
fn stats_rolling_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_stats_rolling);
}

#[test]
fn stats_cumulative_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_stats_cumulative);
}

#[test]
fn stats_time_weighted_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_stats_time_weighted);
}
