//! Ahead-of-time code generation: compile a wired graph's schedule to Rust.
//!
//! [`generate`] walks a wired graph and emits a standalone Rust source file
//! containing a *static schedule*: the dispatch order, tick propagation and
//! active edges are compiled into straight-line code instead of being
//! interpreted by the engine's dirty-list/layer machinery at runtime. Node
//! behaviour (including closures captured by `map`, `filter`, etc.) stays in
//! your wiring code — the generated `run` function takes the same root nodes
//! that [`Graph`](crate::Graph) would and re-wires them deterministically.
//!
//! What is compiled away: per-cycle layer vectors, dirty-node lists,
//! downstream edge iteration and node-index hashing. What remains at runtime
//! is [`StaticRuntime`], a thin shim over the engine's clock/callback
//! management (scheduled callbacks, ready callbacks from threaded sources,
//! lifecycle and error contexts) which shares its implementation with the
//! interpreted engine so the two cannot drift semantically.
//!
//! # Workflow
//!
//! ```
//! use std::time::Duration;
//! use wingfoil::*;
//!
//! // Your wiring function, unchanged.
//! fn wire() -> std::rc::Rc<dyn Node> {
//!     ticker(Duration::from_millis(10)).count().print().as_node()
//! }
//!
//! // One-off (a small bin, example, or build step): emit the static runner.
//! let source = wingfoil::codegen::generate(vec![wire()], &Default::default()).unwrap();
//! assert!(source.starts_with("// @generated by wingfoil::codegen"));
//! // std::fs::write("src/generated.rs", source)?;
//!
//! // In the application, the generated file replaces Graph::run:
//! //     mod generated;
//! //     generated::run(vec![wire()], RunMode::RealTime, RunFor::Forever)?;
//! ```
//!
//! The generated `run` guards against wiring drift: it re-derives a
//! fingerprint of the topology (node types, edges, active flags) and fails
//! with a "regenerate" error if it no longer matches the compiled schedule.
//!
//! # Limitations
//!
//! - Dynamic graph changes (`add_upstream` / `remove_node`, behind the
//!   `dynamic-graph` feature) are rejected at runtime — a compiled schedule
//!   cannot change shape. Use the interpreted engine for those graphs.
//! - The wiring function must produce the same topology as at generation
//!   time; the fingerprint guard turns a mismatch into an error at startup.

use std::fmt::Write as _;
use std::rc::Rc;

use crate::graph::{Graph, RunBounds, first_error};
use crate::types::{NanoTime, Node};
use crate::{RunFor, RunMode};

/// Result alias used by generated code, so consuming crates don't need a
/// direct `anyhow` dependency.
pub type Result<T> = anyhow::Result<T>;

/// Options for [`generate`].
#[derive(Debug, Clone)]
pub struct CodegenOptions {
    /// Name of the generated entry-point function. Default: `"run"`.
    pub function_name: String,
}

impl Default for CodegenOptions {
    fn default() -> Self {
        Self {
            function_name: "run".to_string(),
        }
    }
}

/// The runtime shim driven by generated static runners.
///
/// Owns a fully wired [`Graph`] and exposes the engine's run-loop primitives
/// (`begin_cycle` / `cycle_node` / `end_cycle` / lifecycle) without the
/// interpreted scheduler: tick propagation is the generated caller's job.
/// All time and callback semantics are shared with [`Graph::run`], so a graph
/// produces identical results under both engines.
pub struct StaticRuntime {
    graph: Graph,
    bounds: Option<RunBounds>,
    is_realtime: bool,
    cycles: u32,
}

impl StaticRuntime {
    /// Wire `roots` (exactly as [`Graph::new`] would) and prepare a static
    /// run. Surfaces wiring errors (e.g. a cycle) immediately.
    pub fn new(roots: Vec<Rc<dyn Node>>, run_mode: RunMode, run_for: RunFor) -> Result<Self> {
        let mut graph = Graph::new(roots, run_mode, run_for);
        if let Some(e) = graph.take_wiring_error() {
            return Err(e);
        }
        Ok(Self {
            graph,
            bounds: None,
            is_realtime: matches!(run_mode, RunMode::RealTime),
            cycles: 0,
        })
    }

    /// Number of nodes in the wired graph.
    pub fn node_count(&self) -> usize {
        self.graph.node_count()
    }

    /// Verify the wired topology still matches the one the calling schedule
    /// was generated from. Generated runners call this before [`run`](Self::run).
    pub fn check_topology(&self, expected_nodes: usize, expected_fingerprint: u64) -> Result<()> {
        let actual_nodes = self.graph.node_count();
        let actual_fingerprint = fingerprint(&self.graph);
        if actual_nodes != expected_nodes || actual_fingerprint != expected_fingerprint {
            anyhow::bail!(
                "graph topology does not match this generated static runner: expected \
                 {expected_nodes} nodes with fingerprint {expected_fingerprint:#018x}, wired \
                 {actual_nodes} nodes with fingerprint {actual_fingerprint:#018x}. The wiring has \
                 changed since the runner was generated — regenerate it with \
                 wingfoil::codegen::generate. Wired topology:\n{}",
                topology_table(&self.graph)
            );
        }
        Ok(())
    }

    /// Execute a full run with `run_cycles` as the schedule: the generated
    /// `*_cycles` function (or any closure driving `begin_cycle` /
    /// `cycle_node` / `end_cycle`).
    ///
    /// Owns the whole lifecycle with the same guarantees as [`Graph::run`]:
    /// once `start` is attempted, `stop` and `teardown` always run — even if
    /// `start` or the run loop errors — and the first failure in lifecycle
    /// order is primary with later ones attached.
    pub fn run(&mut self, run_cycles: impl FnOnce(&mut StaticRuntime) -> Result<()>) -> Result<()> {
        self.graph.setup_nodes()?;
        let start_result = self.graph.start_nodes();
        // Skip the run loop if any node failed to start, but still stop and
        // tear down so partially-started nodes get cleaned up.
        let run_result = if start_result.is_ok() {
            run_cycles(self)
        } else {
            Ok(())
        };
        let stop_result = self.graph.stop_nodes();
        let teardown_result = self.graph.teardown_nodes();
        first_error([start_result, run_result, stop_result, teardown_result])
    }

    /// Advance to the next cycle: process due callbacks (marking their nodes
    /// dirty) and advance engine time. Returns `Ok(false)` when the run is
    /// complete. Identical semantics to the interpreted engine's loop head.
    pub fn begin_cycle(&mut self) -> Result<bool> {
        if self.bounds.is_none() {
            self.bounds = Some(self.graph.begin_run());
        }
        let bounds = self.bounds.expect("bounds initialised above");
        self.graph.advance(self.cycles, &bounds, self.is_realtime)
    }

    /// True if `index` was marked dirty by callback processing this cycle
    /// (scheduled callbacks, always-callbacks, or ready callbacks from
    /// threaded sources).
    pub fn is_dirty(&self, index: usize) -> bool {
        self.graph.is_node_dirty(index)
    }

    /// Cycle one node and return whether it ticked. Does **not** propagate
    /// the tick — the generated schedule does that statically.
    pub fn cycle_node(&mut self, index: usize) -> Result<bool> {
        self.graph.cycle_node_inner(index)
    }

    /// Finish the current cycle: clear per-cycle tick/dirty state.
    ///
    /// Errors if a node requested a dynamic graph change during the cycle —
    /// a compiled schedule cannot change shape.
    pub fn end_cycle(&mut self) -> Result<()> {
        #[cfg(feature = "dynamic-graph")]
        if self.graph.has_pending_dynamic_changes() {
            anyhow::bail!(
                "dynamic graph changes (add_upstream/remove_node) are not supported by a \
                 generated static runner; run this graph with the interpreted engine \
                 (Graph::run) instead"
            );
        }
        self.graph.reset();
        self.cycles += 1;
        Ok(())
    }
}

/// Strip generic parameters from a type name: `MapStream<u64, bool>` →
/// `MapStream`. Keeps generated output stable across compiler versions
/// (closure type names inside generics are compiler-dependent).
fn short_type_name(full: &str) -> &str {
    full.split('<').next().unwrap_or(full).trim()
}

/// FNV-1a hash of the wired topology: sanitized node type names plus active
/// and passive upstream index lists. Computed identically at generation time
/// (baked into the emitted `check_topology` call) and at runtime.
fn fingerprint(graph: &Graph) -> u64 {
    const OFFSET: u64 = 0xcbf2_9ce4_8422_2325;
    const PRIME: u64 = 0x0000_0100_0000_01b3;
    let mut canonical = String::new();
    for i in 0..graph.node_count() {
        let name = graph.node_type_name(i);
        let _ = writeln!(
            canonical,
            "{i}|{}|a{:?}|p{:?}",
            short_type_name(&name),
            graph.active_upstream_indices(i),
            graph.passive_upstream_indices(i),
        );
    }
    let mut hash = OFFSET;
    for byte in canonical.bytes() {
        hash ^= byte as u64;
        hash = hash.wrapping_mul(PRIME);
    }
    hash
}

/// Human-readable topology table: one line per node with layer, sanitized
/// type name and upstream edges. Used in the generated file header and in
/// `check_topology` mismatch errors.
fn topology_table(graph: &Graph) -> String {
    let names: Vec<String> = (0..graph.node_count())
        .map(|i| short_type_name(&graph.node_type_name(i)).to_string())
        .collect();
    let name_width = names.iter().map(String::len).max().unwrap_or(0);
    let mut out = String::new();
    let _ = writeln!(
        out,
        "index  layer  {:name_width$}  active upstreams",
        "node"
    );
    for (i, name) in names.iter().enumerate() {
        let actives = graph.active_upstream_indices(i);
        let passives = graph.passive_upstream_indices(i);
        let mut edges = if actives.is_empty() && passives.is_empty() {
            "(source)".to_string()
        } else {
            format!("{actives:?}")
        };
        if !passives.is_empty() {
            let _ = write!(edges, " (passive: {passives:?})");
        }
        let _ = writeln!(
            out,
            "[{i:02}]   {:<5}  {name:name_width$}  {edges}",
            graph.node_layer(i),
        );
    }
    out
}

/// Generate a standalone Rust source file containing a static runner for the
/// graph reachable from `roots`.
///
/// The emitted file exposes `pub fn <function_name>(roots, run_mode, run_for)`
/// with the same behaviour as wiring `roots` into a [`Graph`] and calling
/// [`Graph::run`], but with the schedule compiled to straight-line code. Write
/// it into your crate (e.g. `src/generated.rs`), declare it as a module, and
/// call it with root nodes produced by the *same wiring code* used here.
pub fn generate(roots: Vec<Rc<dyn Node>>, options: &CodegenOptions) -> Result<String> {
    // Run mode / bounds are irrelevant for wiring; use inert values.
    let mut graph = Graph::new(
        roots,
        RunMode::HistoricalFrom(NanoTime::ZERO),
        RunFor::Forever,
    );
    if let Some(e) = graph.take_wiring_error() {
        return Err(e);
    }
    let n = graph.node_count();
    let fp = fingerprint(&graph);
    let fn_name = &options.function_name;

    let names: Vec<String> = (0..n)
        .map(|i| short_type_name(&graph.node_type_name(i)).to_string())
        .collect();
    let active_ups: Vec<Vec<usize>> = (0..n).map(|i| graph.active_upstream_indices(i)).collect();
    let mut has_active_downstream = vec![false; n];
    for ups in &active_ups {
        for &u in ups {
            has_active_downstream[u] = true;
        }
    }

    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(w, "// @generated by wingfoil::codegen. DO NOT EDIT.");
    let _ = writeln!(w, "//");
    let _ = writeln!(
        w,
        "// Static runner for a wingfoil graph with {n} nodes. Rebuild the same graph"
    );
    let _ = writeln!(
        w,
        "// and pass its root nodes to `{fn_name}`; the schedule below is specialised to"
    );
    let _ = writeln!(
        w,
        "// this exact topology. If the wiring changes, regenerate this file."
    );
    let _ = writeln!(w, "//");
    for line in topology_table(&graph).lines() {
        let _ = writeln!(w, "// {line}");
    }
    let _ = writeln!(w);
    let _ = writeln!(w, "use std::rc::Rc;");
    let _ = writeln!(w, "use wingfoil::codegen::StaticRuntime;");
    let _ = writeln!(w, "use wingfoil::{{Node, RunFor, RunMode}};");
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "/// Runs the graph rooted at `roots` using the statically compiled schedule below."
    );
    let _ = writeln!(w, "#[rustfmt::skip]");
    let _ = writeln!(w, "pub fn {fn_name}(");
    let _ = writeln!(w, "    roots: Vec<Rc<dyn Node>>,");
    let _ = writeln!(w, "    run_mode: RunMode,");
    let _ = writeln!(w, "    run_for: RunFor,");
    let _ = writeln!(w, ") -> wingfoil::codegen::Result<()> {{");
    let _ = writeln!(
        w,
        "    let mut rt = StaticRuntime::new(roots, run_mode, run_for)?;"
    );
    let _ = writeln!(w, "    rt.check_topology({n}, {fp:#018x})?;");
    let _ = writeln!(w, "    rt.run({fn_name}_cycles)");
    let _ = writeln!(w, "}}");
    let _ = writeln!(w);
    let _ = writeln!(w, "#[rustfmt::skip]");
    let _ = writeln!(
        w,
        "fn {fn_name}_cycles(rt: &mut StaticRuntime) -> wingfoil::codegen::Result<()> {{"
    );
    let _ = writeln!(w, "    while rt.begin_cycle()? {{");

    // One dispatch line per node, in wiring (topological) order. Ticks
    // propagate through `ticked_*` locals along active edges; `is_dirty`
    // covers callback-driven activation (tickers, delay, feedback, threaded
    // sources). Passive edges generate nothing.
    let mut lines: Vec<(String, String)> = Vec::with_capacity(n);
    for i in 0..n {
        let mut cond_parts: Vec<String> = active_ups[i]
            .iter()
            .map(|u| format!("ticked_{u}"))
            .collect();
        cond_parts.push(format!("rt.is_dirty({i})"));
        let cond = cond_parts.join(" || ");
        let code = if has_active_downstream[i] {
            if active_ups[i].is_empty() {
                format!("let ticked_{i} = {cond} && rt.cycle_node({i})?;")
            } else {
                format!("let ticked_{i} = ({cond}) && rt.cycle_node({i})?;")
            }
        } else {
            format!("if {cond} {{ rt.cycle_node({i})?; }}")
        };
        lines.push((code, format!("// [{i:02}] {}", names[i])));
    }
    let code_width = lines.iter().map(|(code, _)| code.len()).max().unwrap_or(0);
    for (code, comment) in &lines {
        let _ = writeln!(w, "        {code:code_width$}  {comment}");
    }

    let _ = writeln!(w, "        rt.end_cycle()?;");
    let _ = writeln!(w, "    }}");
    let _ = writeln!(w, "    Ok(())");
    let _ = writeln!(w, "}}");
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ValueAt;
    use crate::nodes::*;
    use crate::types::*;
    use std::time::Duration;

    /// Drive a `StaticRuntime` exactly the way generated code does, but with
    /// the schedule interpreted from the wired topology instead of unrolled.
    /// This exercises the runtime shim's semantics for arbitrary graphs.
    fn drive_static(
        roots: Vec<Rc<dyn Node>>,
        run_mode: RunMode,
        run_for: RunFor,
    ) -> anyhow::Result<()> {
        let probe = Graph::new(roots.clone(), run_mode, run_for);
        let n = probe.node_count();
        let ups: Vec<Vec<usize>> = (0..n).map(|i| probe.active_upstream_indices(i)).collect();
        drop(probe);

        let mut rt = StaticRuntime::new(roots, run_mode, run_for)?;
        rt.run(|rt| {
            let mut ticked = vec![false; n];
            while rt.begin_cycle()? {
                for i in 0..n {
                    let due = rt.is_dirty(i) || ups[i].iter().any(|&u| ticked[u]);
                    ticked[i] = due && rt.cycle_node(i)?;
                }
                rt.end_cycle()?;
            }
            Ok(())
        })
    }

    /// Delay where the delay (100ns) far exceeds the tick period (10ns), so
    /// most delayed emissions happen on cycles where the delay node's
    /// upstream did NOT tick — activation comes purely from its scheduled
    /// callback (`is_dirty`), the interesting path for a static schedule.
    fn wire_delay() -> (Vec<Rc<dyn Node>>, Rc<dyn Stream<Vec<ValueAt<u64>>>>) {
        let delayed = ticker(Duration::from_nanos(10))
            .count()
            .delay(Duration::from_nanos(100))
            .collect();
        (vec![delayed.clone().as_node()], delayed)
    }

    #[test]
    fn static_runtime_matches_interpreted_delay() {
        let run_mode = RunMode::HistoricalFrom(NanoTime::ZERO);
        let run_for = RunFor::Duration(Duration::from_nanos(120));

        let (roots, values) = wire_delay();
        Graph::new(roots, run_mode, run_for).run().unwrap();
        let expected = values.peek_value();
        // Sanity-check against the known behaviour (see delay.rs tests): the
        // first delayed value lands at t=100 despite sourcing from t=0.
        assert_eq!(1, expected[0].value);
        assert_eq!(NanoTime::new(100), expected[0].time);
        assert!(expected.len() >= 4);

        let (roots, values) = wire_delay();
        drive_static(roots, run_mode, run_for).unwrap();
        assert_eq!(expected, values.peek_value());
    }

    /// Passive read of a delayed stream (`delay_initializes_to_first_value`
    /// from delay.rs, run through the static runtime).
    #[test]
    fn static_runtime_matches_interpreted_delay_passive() {
        fn wire() -> (Vec<Rc<dyn Node>>, Rc<dyn Stream<Vec<i64>>>) {
            let source = ticker(Duration::from_secs(1)).count().map(|x| x as i64 + 4);
            let delayed = source.delay(Duration::from_secs(5));
            let diff = bimap(Dep::Active(source), Dep::Passive(delayed), |a, b| a - b);
            let acc = diff.accumulate();
            (vec![acc.clone().as_node()], acc)
        }
        let run_mode = RunMode::HistoricalFrom(NanoTime::ZERO);
        let run_for = RunFor::Duration(Duration::from_secs(8));

        let (roots, values) = wire();
        Graph::new(roots, run_mode, run_for).run().unwrap();
        let expected = values.peek_value();
        assert_eq!(vec![0, 1, 2, 3, 4, 5, 5, 5, 5, 5], expected);

        let (roots, values) = wire();
        drive_static(roots, run_mode, run_for).unwrap();
        assert_eq!(expected, values.peek_value());
    }

    fn wire_pipeline() -> (Rc<dyn Node>, Rc<dyn Stream<Vec<u64>>>) {
        let source = ticker(Duration::from_nanos(100)).count();
        let evens = source.clone().filter(source.map(|i| i % 2 == 0));
        let acc = evens.map(|i| i * 10).accumulate();
        (acc.clone().as_node(), acc)
    }

    #[test]
    fn static_runtime_matches_interpreted_pipeline() {
        let (root, values) = wire_pipeline();
        root.run(RunMode::HistoricalFrom(NanoTime::ZERO), RunFor::Cycles(10))
            .unwrap();
        let expected = values.peek_value();
        assert!(!expected.is_empty());

        let (root, values) = wire_pipeline();
        drive_static(
            vec![root],
            RunMode::HistoricalFrom(NanoTime::ZERO),
            RunFor::Cycles(10),
        )
        .unwrap();
        assert_eq!(expected, values.peek_value());
    }

    fn wire_feedback() -> (Vec<Rc<dyn Node>>, Rc<dyn Stream<Vec<u64>>>) {
        let (tx, rx) = feedback::<u64>();
        let source = ticker(Duration::from_nanos(100)).count();
        let value = bimap(
            crate::Dep::Active(source),
            crate::Dep::Passive(rx),
            |src, fb| src + fb * 10,
        );
        let fb = value.feedback(tx);
        let acc = value.accumulate();
        (vec![fb.as_node(), acc.clone().as_node()], acc)
    }

    #[test]
    fn static_runtime_matches_interpreted_feedback() {
        let (roots, values) = wire_feedback();
        Graph::new(
            roots,
            RunMode::HistoricalFrom(NanoTime::ZERO),
            RunFor::Duration(Duration::from_nanos(500)),
        )
        .run()
        .unwrap();
        let expected = values.peek_value();
        assert_eq!(vec![1, 12, 123, 1234, 12345, 123456], expected);

        let (roots, values) = wire_feedback();
        drive_static(
            roots,
            RunMode::HistoricalFrom(NanoTime::ZERO),
            RunFor::Duration(Duration::from_nanos(500)),
        )
        .unwrap();
        assert_eq!(expected, values.peek_value());
    }

    #[test]
    fn static_runtime_works_in_realtime() {
        let source = ticker(Duration::from_millis(1)).count();
        drive_static(
            vec![source.clone().as_node()],
            RunMode::RealTime,
            RunFor::Cycles(3),
        )
        .unwrap();
        assert_eq!(3, source.peek_value());
    }

    #[test]
    fn generate_is_deterministic() {
        let (root, _) = wire_pipeline();
        let a = generate(vec![root], &CodegenOptions::default()).unwrap();
        let (root, _) = wire_pipeline();
        let b = generate(vec![root], &CodegenOptions::default()).unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn generate_emits_expected_shape() {
        let (root, _) = wire_pipeline();
        let src = generate(vec![root], &CodegenOptions::default()).unwrap();
        assert!(src.starts_with("// @generated by wingfoil::codegen"));
        assert!(src.contains("pub fn run("));
        assert!(src.contains("rt.check_topology("));
        assert!(src.contains("while rt.begin_cycle()? {"));
        assert!(src.contains("rt.end_cycle()?;"));
        // Sources have no propagation inputs.
        assert!(src.contains("let ticked_0 = rt.is_dirty(0) && rt.cycle_node(0)?;"));
    }

    #[test]
    fn generate_honours_function_name() {
        let (root, _) = wire_pipeline();
        let opts = CodegenOptions {
            function_name: "run_pricing".to_string(),
        };
        let src = generate(vec![root], &opts).unwrap();
        assert!(src.contains("pub fn run_pricing("));
        assert!(src.contains("fn run_pricing_cycles("));
    }

    #[test]
    fn check_topology_rejects_different_graph() {
        let (root, _) = wire_pipeline();
        let rt = StaticRuntime::new(
            vec![root],
            RunMode::HistoricalFrom(NanoTime::ZERO),
            RunFor::Cycles(1),
        )
        .unwrap();
        let n = rt.node_count();
        // Correct count, wrong fingerprint → must fail with a regenerate hint.
        let err = rt.check_topology(n, 0).expect_err("fingerprint mismatch");
        assert!(format!("{err:#}").contains("regenerate"));
        // Matching fingerprint passes.
        let (root, _) = wire_pipeline();
        let probe = Graph::new(
            vec![root],
            RunMode::HistoricalFrom(NanoTime::ZERO),
            RunFor::Cycles(1),
        );
        rt.check_topology(n, fingerprint(&probe)).unwrap();
    }

    #[test]
    fn wiring_cycle_is_an_error() {
        use std::cell::RefCell;

        struct SelfCycleNode {
            upstream: RefCell<Option<Rc<dyn Node>>>,
        }
        impl MutableNode for SelfCycleNode {
            fn cycle(&mut self, _state: &mut GraphState) -> anyhow::Result<bool> {
                Ok(false)
            }
            fn upstreams(&self) -> UpStreams {
                match &*self.upstream.borrow() {
                    Some(u) => UpStreams::new(vec![u.clone()], vec![]),
                    None => UpStreams::none(),
                }
            }
        }

        let node = Rc::new(RefCell::new(SelfCycleNode {
            upstream: RefCell::new(None),
        }));
        let dyn_node: Rc<dyn Node> = node.clone();
        node.borrow().upstream.replace(Some(dyn_node.clone()));

        let err = generate(vec![dyn_node.clone()], &CodegenOptions::default())
            .expect_err("wiring cycle must fail generation");
        assert!(format!("{err:#}").contains("cycle"));

        let err = StaticRuntime::new(
            vec![dyn_node],
            RunMode::HistoricalFrom(NanoTime::ZERO),
            RunFor::Cycles(1),
        )
        .err()
        .expect("wiring cycle must fail StaticRuntime::new");
        assert!(format!("{err:#}").contains("cycle"));
    }

    #[cfg(feature = "dynamic-graph")]
    #[test]
    fn dynamic_graph_changes_are_rejected() {
        struct DynamicAdder {
            upstream: Rc<dyn Node>,
        }
        impl MutableNode for DynamicAdder {
            fn cycle(&mut self, state: &mut GraphState) -> anyhow::Result<bool> {
                let extra = ticker(Duration::from_nanos(50));
                state.add_upstream(extra, true, false);
                Ok(true)
            }
            fn upstreams(&self) -> UpStreams {
                UpStreams::new(vec![self.upstream.clone()], vec![])
            }
        }

        let source = ticker(Duration::from_nanos(100));
        let node = DynamicAdder { upstream: source }.into_node();
        let err = drive_static(
            vec![node],
            RunMode::HistoricalFrom(NanoTime::ZERO),
            RunFor::Cycles(3),
        )
        .expect_err("dynamic additions must be rejected by the static runner");
        assert!(format!("{err:#}").contains("not supported"));
    }

    #[test]
    fn short_type_name_strips_generics() {
        assert_eq!("MapStream", short_type_name("MapStream<u64, bool>"));
        assert_eq!("TickNode", short_type_name("TickNode"));
    }
}
