/**
 * The bridge between the voice build and the composition.
 *
 * `assets/narration.json` is generated by `scripts/build-voice.py` and carries
 * a measured duration for every scene. Frame counts are derived from it here
 * and nowhere else, which is what makes the voice swappable: drop in new wavs,
 * re-run the script, and every scene re-times itself.
 */

import narration from "../assets/narration.json";

export type Word = { word: string; start: number; end: number };
export type Sentence = { text: string; start: number; end: number };

export type Scene = {
  id: string;
  captions: boolean;
  text: string;
  audio: string;
  audioDuration: number;
  duration: number;
  sentences: Sentence[];
  words: Word[];
};

export const FPS = narration.fps;
export const scenes = narration.scenes as Scene[];

/** Frames a scene occupies. At least one frame, so a stub wav cannot zero it. */
export const framesFor = (scene: Scene): number =>
  Math.max(1, Math.round(scene.duration * FPS));

/** Cumulative start frame of each scene, in order. */
export const layout = (): { scene: Scene; from: number; durationInFrames: number }[] => {
  let from = 0;
  return scenes.map((scene) => {
    const durationInFrames = framesFor(scene);
    const entry = { scene, from, durationInFrames };
    from += durationInFrames;
    return entry;
  });
};

export const totalFrames = (): number =>
  scenes.reduce((n, scene) => n + framesFor(scene), 0);

export const sceneById = (id: string): Scene => {
  const found = scenes.find((s) => s.id === id);
  if (!found) {
    throw new Error(`no scene ${id} in narration.json -- re-run scripts/build-voice.py`);
  }
  return found;
};
