"""Python round-trip tests for the wingfoil_next interop module.

These exercise the real extension module (built by maturin), proving the erased
object form is reachable and composable from Python: native values in, native
values out, Python callables wired into the graph, and run errors surfaced as
exceptions.
"""

import pytest

import wingfoil_next as wf


def test_constant_maps_via_python_lambda():
    g = wf.Graph()
    out = g.constant(4.0).map(lambda x: x * x)
    g.run(cycles=1)
    assert out.value() == 16.0


def test_values_source_replays_a_sequence():
    g = wf.Graph()
    out = g.values([10, 20, 30], period_nanos=100).accumulate()
    g.run(cycles=3)
    assert out.value() == [10, 20, 30]


def test_values_source_feeds_combinators():
    # Feed real data from Python, run it through a chain.
    g = wf.Graph()
    out = g.values([1, 2, 3, 4], period_nanos=100).filter_value(lambda n: n % 2 == 0).sum()
    g.run(cycles=4)
    assert out.value() == 6.0  # keep 2, 4 -> cumulative sum 6


def test_values_source_carries_strings():
    g = wf.Graph()
    out = g.values(["a", "b", "c"], period_nanos=100).map(lambda s: s.upper()).accumulate()
    g.run(cycles=3)
    assert out.value() == ["A", "B", "C"]


def test_counter_source_ticks():
    g = wf.Graph()
    doubled = g.counter(period_nanos=100).map(lambda n: n * 2)
    g.run(cycles=3)
    assert doubled.value() == 6  # 3rd tick -> 3 * 2


def test_filter_by_python_predicate():
    g = wf.Graph()
    counter = g.counter(period_nanos=100)
    keep = counter.map(lambda n: n > 2)
    filtered = counter.filter(keep)
    g.run(cycles=5)
    # last passing value is the 5th tick
    assert filtered.value() == 5


def test_distinct_suppresses_duplicates():
    g = wf.Graph()
    # 1,2,3,4 -> n//2 -> 0,1,1,2 -> distinct passes changes only; final value 2
    stepped = g.counter(period_nanos=100).map(lambda n: n // 2).distinct()
    g.run(cycles=4)
    assert stepped.value() == 2


def test_map_callable_exception_aborts_run():
    g = wf.Graph()
    g.constant("not a number").map(lambda x: x + 1)
    with pytest.raises(RuntimeError, match="Python map callable raised"):
        g.run(cycles=1)


def test_graph_reruns_and_resets():
    # A re-runnable graph can be run repeatedly; the engine resets node state
    # between runs, so it reproduces the same values.
    g = wf.Graph()
    out = g.constant(2.0).map(lambda x: x + 1)
    g.run(cycles=1)
    assert out.value() == 3.0
    g.run(cycles=1)
    assert out.value() == 3.0


def test_native_types_round_trip():
    g = wf.Graph()
    out = g.constant("hello").map(lambda s: s.upper())
    g.run(cycles=1)
    assert out.value() == "HELLO"


def test_user_op_scale():
    # `scale` is a Rust-authored op (via pyop!), called as a free function.
    g = wf.Graph()
    out = wf.scale(g.constant(3.0), 4.0)
    g.run(cycles=1)
    assert out.value() == 12.0


def test_user_op_composes_with_builtins():
    # The "extend in Python" thesis: a Rust user op wired between built-in
    # combinators. counter 1..5 -> scale x10 -> 10,20,30,40,50 -> keep > 25.
    g = wf.Graph()
    scaled = wf.scale(g.counter(period_nanos=100), 10.0)
    keep = scaled.map(lambda x: x > 25)
    out = scaled.filter(keep)
    g.run(cycles=5)
    assert out.value() == 50.0


def test_pyop_macro_op_square():
    # `square` is generated by the #[pyop] proc macro from an Op impl.
    g = wf.Graph()
    out = wf.square(g.constant(5.0))
    g.run(cycles=1)
    assert out.value() == 25.0


def test_pyop_stateful_running_total():
    # running_total is a stateful #[pyop] (accumulator in the op's State).
    g = wf.Graph()
    out = wf.running_total(g.counter(period_nanos=100))  # 1,2,3 -> 1,3,6
    g.run(cycles=3)
    assert out.value() == 6.0


def test_pyop_stateful_state_reseeds_on_rerun():
    g = wf.Graph()
    out = wf.running_total(g.counter(period_nanos=100))
    g.run(cycles=3)
    assert out.value() == 6.0
    g.run(cycles=3)  # engine re-seeds State from Default (0.0); restart, not continue
    assert out.value() == 6.0


def test_pyadapter_source():
    # ramp_source is a Rust source adapter (#[pyadapter]) exposed as a callable.
    g = wf.Graph()
    out = wf.ramp_source(g, 10.0, 2.0).accumulate()
    g.run(cycles=3)
    # start=10, step=2 -> 10, 12, 14
    assert out.value() == [10.0, 12.0, 14.0]


def test_pyadapter_sink():
    # list_sink is a Rust sink adapter (#[pyadapter], no source marker): it
    # consumes the stream into a Python list.
    out = []
    g = wf.Graph()
    wf.list_sink(g.counter(period_nanos=100), out)  # counter 1,2,3 -> f64
    g.run(cycles=3)
    assert out == [1.0, 2.0, 3.0]


def test_pyadapter_source_and_sink_together():
    out = []
    g = wf.Graph()
    wf.list_sink(wf.ramp_source(g, 10.0, 5.0), out)  # 10, 15, 20
    g.run(cycles=3)
    assert out == [10.0, 15.0, 20.0]


def test_pyadapter_burst_source():
    # pair_source is a burst-shaped source adapter: each tick is a Burst<f64> of
    # two same-instant values, which erases to a Python list.
    g = wf.Graph()
    out = wf.pair_source(g).accumulate()
    g.run(cycles=3)
    assert out.value() == [[1.0, 10.0], [2.0, 20.0], [3.0, 30.0]]


def test_pyadapter_source_feeds_combinators():
    g = wf.Graph()
    out = wf.ramp_source(g, 1.0, 1.0).sum()  # 1,2,3 -> cumulative 1,3,6
    g.run(cycles=3)
    assert out.value() == 6.0


def test_pygraph_reuses_a_rust_subgraph():
    # doubled_running_total is a Rust-authored sub-graph (#[pygraph]) spliced in.
    g = wf.Graph()
    out = wf.doubled_running_total(g.counter(period_nanos=100))
    g.run(cycles=3)
    # 1,2,3 -> double -> 2,4,6 -> cumulative sum -> 2,6,12
    assert out.value() == 12.0


def test_pyop_two_input_op():
    # weighted_add is a two-input #[pyop]: module.weighted_add(stream, other).
    g = wf.Graph()
    a = g.counter(period_nanos=100)  # 1,2,3
    b = g.counter(period_nanos=100).map(lambda n: n * 10)  # 10,20,30
    out = wf.weighted_add(a, b)
    g.run(cycles=3)
    assert out.value() == 33.0  # 3 + 30


def test_pyop_and_pyop_fn_compose():
    # Both macro forms, chained: counter -> square -> scale x2.
    g = wf.Graph()
    out = wf.scale(wf.square(g.counter(period_nanos=100)), 2.0)
    g.run(cycles=3)  # 3rd tick: 3^2 * 2
    assert out.value() == 18.0


def test_custom_node_python_object_as_graph_node():
    # A Python object acting as a graph node (the classic CustomStream shape):
    # sum two upstream counters each cycle via the cycle(values)/peek protocol.
    class Adder:
        def __init__(self):
            self.total = 0

        def cycle(self, values):
            self.total = sum(values)
            return True

        def peek(self):
            return self.total

    g = wf.Graph()
    a = g.counter(period_nanos=100)
    b = g.counter(period_nanos=100)
    summed = g.custom_node([a, b], Adder())
    g.run(cycles=3)
    assert summed.value() == 6  # 3rd tick: 3 + 3


def test_custom_node_can_stay_quiet():
    # Returning False from cycle suppresses the tick (classic "did I tick?").
    class Evens:
        def __init__(self):
            self.v = 0

        def cycle(self, values):
            self.v = values[0]
            return self.v % 2 == 0

        def peek(self):
            return self.v

    g = wf.Graph()
    evens = g.custom_node([g.counter(period_nanos=100)], Evens())
    g.run(cycles=6)
    assert evens.value() == 6  # last even value passed through


def test_custom_node_exception_aborts_run():
    class Boom:
        def cycle(self, values):
            raise ValueError("boom")

        def peek(self):
            return 0

    g = wf.Graph()
    g.custom_node([g.counter(period_nanos=100)], Boom())
    with pytest.raises(RuntimeError, match="Python custom node cycle raised"):
        g.run(cycles=1)


def test_count_ignores_values():
    g = wf.Graph()
    out = g.counter(period_nanos=100).map(lambda n: "x").count()
    g.run(cycles=3)
    assert out.value() == 3


def test_limit_caps_ticks():
    g = wf.Graph()
    out = g.counter(period_nanos=100).limit(2)
    g.run(cycles=5)
    assert out.value() == 2  # last value passed before the cap


def test_difference_of_counter_is_one():
    g = wf.Graph()
    out = g.counter(period_nanos=100).difference()
    g.run(cycles=4)
    assert out.value() == 1  # 1,2,3,4 -> deltas 1,1,1


def test_not_negates_value():
    # `not` is arithmetic negation (__neg__) and is a Python keyword.
    g = wf.Graph()
    out = getattr(g.constant(5), "not")()
    g.run(cycles=1)
    assert out.value() == -5


def test_sample_emits_held_value_on_trigger():
    # A constant (ticks once) sampled on every counter tick re-emits its value.
    g = wf.Graph()
    held = g.constant(42)
    out = held.sample(g.counter(period_nanos=100))
    g.run(cycles=3)
    assert out.value() == 42


def test_throttle_rate_limits():
    # counter ticks 1..9 at 100..900; throttle(250) emits at 100, 400, 700.
    g = wf.Graph()
    out = g.counter(period_nanos=100).throttle(250)
    g.run(cycles=9)
    assert out.value() == 7  # last emission at t=700


def test_inspect_taps_and_passes_through():
    seen = []
    g = wf.Graph()
    out = g.counter(period_nanos=100).inspect(seen.append)
    g.run(cycles=3)
    assert seen == [1, 2, 3]
    assert out.value() == 3


def test_inspect_exception_aborts_run():
    def boom(v):
        raise ValueError("boom")

    g = wf.Graph()
    g.counter(period_nanos=100).inspect(boom)
    with pytest.raises(RuntimeError, match="Python inspect callable raised"):
        g.run(cycles=1)


def test_accumulate_grows_a_list():
    g = wf.Graph()
    out = g.counter(period_nanos=100).accumulate()
    g.run(cycles=3)
    assert out.value() == [1, 2, 3]


def test_buffer_flushes_at_capacity():
    g = wf.Graph()
    out = g.counter(period_nanos=100).buffer(2)
    g.run(cycles=4)
    assert out.value() == [3, 4]  # last full flush


def test_window_flushes_on_interval():
    g = wf.Graph()
    out = g.counter(period_nanos=100).window(interval_nanos=200)
    g.run(cycles=6)
    assert out.value() == [5, 6]  # last window boundary flush


def test_with_time_pairs_nanos_and_value():
    g = wf.Graph()
    out = g.counter(period_nanos=100).with_time()
    g.run(cycles=3)
    assert out.value() == (200, 3)  # ticks at t=0,100,200


def test_collect_gathers_time_value_tuples():
    g = wf.Graph()
    out = g.counter(period_nanos=100).collect()
    g.run(cycles=2)
    assert out.value() == [(0, 1), (100, 2)]


def test_fold_accumulates():
    g = wf.Graph()
    out = g.counter(period_nanos=100).fold(0, lambda acc, v: acc + v)
    g.run(cycles=3)
    assert out.value() == 6  # 1+2+3


def test_fold_restarts_on_rerun():
    g = wf.Graph()
    out = g.counter(period_nanos=100).fold(0, lambda acc, v: acc + v)
    g.run(cycles=3)
    assert out.value() == 6
    g.run(cycles=3)  # engine re-seeds the accumulator; restart, not continue
    assert out.value() == 6


def test_fold_exception_aborts_run():
    def boom(acc, v):
        raise ValueError("boom")

    g = wf.Graph()
    g.counter(period_nanos=100).fold(0, boom)
    with pytest.raises(RuntimeError, match="Python fold callable raised"):
        g.run(cycles=1)


def test_filter_map_keeps_non_none():
    g = wf.Graph()
    out = g.counter(period_nanos=100).filter_map(
        lambda n: n * 10 if n % 2 == 0 else None
    )
    g.run(cycles=4)
    assert out.value() == 40  # even counts scaled: 20, 40


def test_filter_value_keeps_on_predicate():
    g = wf.Graph()
    out = g.counter(period_nanos=100).filter_value(lambda n: n > 2)
    g.run(cycles=5)
    assert out.value() == 5  # 3, 4, 5 pass


def test_filter_none_drops_python_none():
    g = wf.Graph()
    out = g.counter(period_nanos=100).map(
        lambda n: n if n % 2 == 0 else None
    ).filter_none()
    g.run(cycles=6)
    assert out.value() == 6  # 2, 4, 6 pass


def test_sum_is_cumulative():
    g = wf.Graph()
    out = g.counter(period_nanos=100).sum()
    g.run(cycles=4)
    assert out.value() == 10.0  # 1+2+3+4


def test_mean_and_average_are_cumulative():
    g = wf.Graph()
    out = g.counter(period_nanos=100).mean()
    avg = g.counter(period_nanos=100).average()
    g.run(cycles=4)
    assert out.value() == 2.5  # (1+2+3+4)/4
    assert avg.value() == 2.5  # average is an alias for mean


def test_sum_of_non_numeric_aborts_run():
    g = wf.Graph()
    g.constant("x").sum()
    with pytest.raises(RuntimeError, match="not a f64"):
        g.run(cycles=1)


def test_merge_all_combines_streams():
    g = wf.Graph()
    a = g.counter(period_nanos=300)  # ticks at 0,300,600
    b = g.counter(period_nanos=300).map(lambda n: n + 100)
    c = g.counter(period_nanos=300).map(lambda n: n + 200)
    out = a.merge_all([b, c])
    g.run(cycles=3)  # all tick together; earliest-supplied (a) wins the tie
    assert out.value() == 3  # a's running count


def test_dataframe_from_stream():
    pd = pytest.importorskip("pandas")
    g = wf.Graph()
    df = g.counter(period_nanos=100).dataframe()
    g.run(cycles=3)
    frame = df.value()
    assert isinstance(frame, pd.DataFrame)
    assert list(frame["time"]) == [0, 100, 200]
    assert list(frame["value"]) == [1, 2, 3]


def test_reduce_runs_from_first_value():
    g = wf.Graph()
    out = g.counter(period_nanos=100).reduce(lambda acc, v: acc + v)
    g.run(cycles=3)
    assert out.value() == 6  # 1, then 1+2=3, then 3+3=6


def test_split_decomposes_tuples():
    g = wf.Graph()
    pairs = g.counter(period_nanos=100).map(lambda n: (n, n * 10))
    left, right = pairs.split()
    g.run(cycles=3)
    assert left.value() == 3
    assert right.value() == 30


def test_bimap_combines_two_inputs():
    g = wf.Graph()
    a = g.counter(period_nanos=100)  # 1,2,3
    b = g.counter(period_nanos=100).map(lambda n: n * 10)  # 10,20,30
    out = a.bimap(b, lambda x, y: x + y)
    g.run(cycles=3)
    assert out.value() == 33  # 3 + 30


def test_bimap_exception_aborts_run():
    def boom(x, y):
        raise ValueError("boom")

    g = wf.Graph()
    a = g.counter(period_nanos=100)
    b = g.counter(period_nanos=100)
    a.bimap(b, boom)
    with pytest.raises(RuntimeError, match="Python bimap callable raised"):
        g.run(cycles=1)
