"""Python round-trip tests for the wingfoil_next interop module.

These exercise the real extension module (built by maturin), proving the erased
object form is reachable and composable from Python: native values in, native
values out, Python callables wired into the graph, and run errors surfaced as
exceptions.
"""

import pytest

import wingfoil_next as wf


def test_constant_maps_via_python_lambda():
    g = wf.Graph()
    out = g.constant(4.0).map(lambda x: x * x)
    g.run(cycles=1)
    assert out.value() == 16.0


def test_counter_source_ticks():
    g = wf.Graph()
    doubled = g.counter(period_nanos=100).map(lambda n: n * 2)
    g.run(cycles=3)
    assert doubled.value() == 6  # 3rd tick -> 3 * 2


def test_filter_by_python_predicate():
    g = wf.Graph()
    counter = g.counter(period_nanos=100)
    keep = counter.map(lambda n: n > 2)
    filtered = counter.filter(keep)
    g.run(cycles=5)
    # last passing value is the 5th tick
    assert filtered.value() == 5


def test_distinct_suppresses_duplicates():
    g = wf.Graph()
    # 1,2,3,4 -> n//2 -> 0,1,1,2 -> distinct passes changes only; final value 2
    stepped = g.counter(period_nanos=100).map(lambda n: n // 2).distinct()
    g.run(cycles=4)
    assert stepped.value() == 2


def test_map_callable_exception_aborts_run():
    g = wf.Graph()
    g.constant("not a number").map(lambda x: x + 1)
    with pytest.raises(RuntimeError, match="Python map callable raised"):
        g.run(cycles=1)


def test_graph_reruns_and_resets():
    # A re-runnable graph can be run repeatedly; the engine resets node state
    # between runs, so it reproduces the same values.
    g = wf.Graph()
    out = g.constant(2.0).map(lambda x: x + 1)
    g.run(cycles=1)
    assert out.value() == 3.0
    g.run(cycles=1)
    assert out.value() == 3.0


def test_native_types_round_trip():
    g = wf.Graph()
    out = g.constant("hello").map(lambda s: s.upper())
    g.run(cycles=1)
    assert out.value() == "HELLO"


def test_user_op_scale():
    # `scale` is a Rust-authored op (via pyop!), called as a free function.
    g = wf.Graph()
    out = wf.scale(g.constant(3.0), 4.0)
    g.run(cycles=1)
    assert out.value() == 12.0


def test_user_op_composes_with_builtins():
    # The "extend in Python" thesis: a Rust user op wired between built-in
    # combinators. counter 1..5 -> scale x10 -> 10,20,30,40,50 -> keep > 25.
    g = wf.Graph()
    scaled = wf.scale(g.counter(period_nanos=100), 10.0)
    keep = scaled.map(lambda x: x > 25)
    out = scaled.filter(keep)
    g.run(cycles=5)
    assert out.value() == 50.0


def test_pyop_macro_op_square():
    # `square` is generated by the #[pyop] proc macro from an Op impl.
    g = wf.Graph()
    out = wf.square(g.constant(5.0))
    g.run(cycles=1)
    assert out.value() == 25.0


def test_pyop_and_pyop_fn_compose():
    # Both macro forms, chained: counter -> square -> scale x2.
    g = wf.Graph()
    out = wf.scale(wf.square(g.counter(period_nanos=100)), 2.0)
    g.run(cycles=3)  # 3rd tick: 3^2 * 2
    assert out.value() == 18.0
