//! Op-completeness guard: protection against **one-sided op registration**,
//! adapted to the forwarder dispatch design.
//!
//! The port plan (Phase 1) called for a `supported_ops!()` list that both the
//! `graph!` parse-match and its "unsupported op" error message consume, plus a
//! test diffing that list against the fluent trait surface. That design is
//! **obsolete**: the `graph!` op *table* was deleted (see
//! `docs/macro-extensibility-decision.md`) — the macro now dispatches through
//! naming-convention forwarders (`__wf_op_<name>_*`, generated by `#[op]`), so
//! there is no central op list to diff and an unknown op simply fails to
//! resolve a forwarder at expansion time.
//!
//! The guard the plan wanted still holds, realized as a **compile-time** test.
//! A combinator *used inside* a `graph!` wiring function only compiles if it
//! has **both**:
//!   * a fluent method (the wiring fn is ordinary fluent code — a missing
//!     method is a compile error), **and**
//!   * a `graph!` forwarder (`#[op]` emits it — a missing one fails to resolve
//!     `__wf_op_<name>_cycle` / `__WF_OP_<NAME>_ACTIVATION` at the call site).
//!
//! So the `graph!` blocks below *are* the two-sided guard: every dual-mode
//! combinator is exercised here, so dropping either side (fluent method or
//! forwarder) breaks this build. Each block also asserts
//! `interpreted() == compiled()`, extending interpreted-vs-compiled parity
//! across the whole combinator surface — the biggest engine-drift surface in
//! the codebase. (`nested()` island parity is covered separately in
//! `nested_islands.rs`.)
//!
//! ## The fluent-only surface (deliberately excluded from the `graph!` blocks)
//!
//! These combinators exist fluently (and run on the interpreted engine) but are
//! **not** used in a `graph!` block above, in three categories. Adding a new op
//! means consciously placing it in a `graph!` block or in one of these lists —
//! never silently in neither.
//!
//! **1. IO / cycle — not expressible by design** (capability matrix `❌`):
//!   * `external`, `channel`, `poll` — IO / threaded / busy-poll sources; the
//!     compiled path runs its own loop with no external wake.
//!   * `feedback` (source + the `feedback` close method) — a cycle in the DAG,
//!     which straight-line compiled emission cannot express (v1 out-of-scope).
//!   * `for_each` — a fallible IO sink; lives at the runtime boundary.
//!
//! **2. Sugar over a primitive — spell the primitive in `graph!`:**
//!   * `merge_all` → a chain of 2-ary `merge`s; `not` → `map(|b| !b)`;
//!     `collapse` → `map_filter`; `split` → two `map`s. (`map_n` / `fan` are
//!     the *exception* — the macro recognises them as repetition sugar, so they
//!     ARE expressible; covered in `surface_sugar` below.)
//!
//! **2b. Ergonomic fluent signature ≠ the op's `Cfg` — fluent-only:**
//!   * `logged` — the `Logged` op's `Cfg` is `(String, log::Level)`, but the
//!     fluent method takes `&str` and converts (so dynamic `format!` labels
//!     work, matching classic). `graph!`/compiled uses the *call-site arg
//!     types* as the `Cfg` verbatim, so the same tokens cannot satisfy both a
//!     `&str` fluent param and a `String` cfg. `#[op(build = logged)]` still
//!     emits forwarders (harmless) and the interpreted `Builder::logged` the
//!     fluent method wires through; it just isn't spelled in a `graph!` block.
//!     A debug/logging tap has no place in a self-driving compiled kernel
//!     anyway, so this costs nothing real.
//!
//! **3. Currently interpreted-only — candidate follow-up, not by design:**
//!   * *(empty — all four former members are now dual-mode.)* `join_passive`,
//!     `try_join_passive`, `delay_with_reset`, and `with_time` were once
//!     interpreted-only for want of a `graph!` forwarder; they now carry one
//!     (see `surface_passive_delay` below, exercised across all three engines)
//!     and moved out of this list. The mechanism, for each:
//!     - `join_passive` / `try_join_passive` — the passive-edge join shape. A
//!       second `#[op]` cannot attach to `Join` / `TryJoin` (only the passive
//!       mask differs), so a thin forwarder-witness op (`JoinPassive` /
//!       `TryJoinPassive` in `ops.rs`, `#[op(passive = [1])]`, delegating its
//!       `cycle` to `Join` / `TryJoin`) emits the `__wf_op_join_passive_*` /
//!       `__wf_op_try_join_passive_*` forwarders.
//!     - `delay_with_reset` — the real op's `In = (&T, bool, bool)` (two tick
//!       flags, the trigger's value unread) is unparseable by `#[op]`; a
//!       witness op (`DelayWithResetFwd`) restates it in the two-edge
//!       `(&T, bool, &U, bool)` form `#[op]` parses and delegates to
//!       `DelayWithReset::cycle`.
//!     - `with_time` — `#[op(build = with_time, no_builder)]` on the op itself
//!       (the hand-written `Builder::with_time` stays for its `T: Clone`-only
//!       interpreted seeding — it is now the catalog's *only* `no_builder`
//!       op; every other shape gets its `Builder` method generated, and the
//!       `bimap`/`trimap` family are extra hand-written methods over the
//!       `Join`/`Join3` ops, not opt-outs). Inside `graph!`/compiled the output must be
//!       `Default` (`(NanoTime, T): Default`), which holds for every value type
//!       used here; the differing pre-first-tick seed is never observed because
//!       the op ticks in lockstep with its source.
//!
//! This file is the single place that classification is written down; the
//! *enforcement* is that everything in category (none) — i.e. every op meant to
//! be dual-mode — compiles in a `graph!` block.

use std::time::Duration;

use wingfoil::{NanoTime, RunFor, RunMode};
use wingfoil_next::prelude::*;

const HISTORICAL: RunMode = RunMode::HistoricalFrom(NanoTime::ZERO);
const P: Duration = Duration::from_millis(10);
const RUN: RunFor = RunFor::Cycles(12);

// The stateless / single-input `u64` surface: `count`, `map`, `map_filter`,
// `distinct`, `difference`, `limit`, `inspect`, `filter` (against a derived
// bool stream), `merge`, and `accumulate`.
wingfoil_next::graph! {
    fn surface_u64(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let mapped = count.map(|i| i * 2);
        let filtered = mapped.map_filter(|i| (*i, *i % 4 == 0));
        let distinct = filtered.distinct();
        let diff = distinct.difference();
        let limited = diff.limit(100);
        let seen = limited.inspect(|_| ());
        let is_even = count.map(|i| i.is_multiple_of(2));
        let evens = count.filter(&is_even);
        let out = seen.merge(&evens).accumulate();
        out
    }
}

// Scheduling / buffering single-input surface: `delay`, `throttle`, `window`,
// `buffer`.
wingfoil_next::graph! {
    fn surface_scheduling(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let delayed = count.delay(Duration::from_millis(25));
        let throttled = delayed.throttle(Duration::from_millis(15));
        let out = throttled.accumulate();
        out
    }
}

// Window / buffer (both emit `Vec<u64>` on a boundary).
wingfoil_next::graph! {
    fn surface_windowing(g: &GraphBuilder) -> Stream<Vec<Vec<u64>>> {
        let count = g.ticker(P).count();
        let windowed = count.window(Duration::from_millis(30));
        let buffered = count.buffer(3);
        let out = windowed.merge(&buffered).accumulate();
        out
    }
}

// Multi-input active surface: `join` and `merge`.
wingfoil_next::graph! {
    fn surface_multi(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let a = count.map(|i| i * 10);
        let b = count.map(|i| i * 100);
        // Param types annotated so inference doesn't explore unrelated blanket
        // `Add` impls (e.g. nalgebra's, pulled in under the `augurs` feature).
        let joined = a.join(&b, |x: &u64, y: &u64| x + y);
        let out = joined.merge(&a).accumulate();
        out
    }
}

// Time / passive-read surface: `ticked_at`, `ticked_at_elapsed`, `sample`.
wingfoil_next::graph! {
    fn surface_time(g: &GraphBuilder) -> Stream<Vec<NanoTime>> {
        let count = g.ticker(P).count();
        let at = count.ticked_at();
        let elapsed = count.ticked_at_elapsed();
        let flag = count.map(|i| i.is_multiple_of(2));
        let trigger = count.filter(&flag).map(|_| ());
        let gated = at.sample(&trigger);
        let out = gated.merge(&elapsed).accumulate();
        out
    }
}

// Fallible active surface: `try_map`, `try_join`.
wingfoil_next::graph! {
    fn surface_fallible(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let tried = count.try_map(|i| Ok(i + 1));
        let other = count.map(|i| i * 2);
        let joined = tried.try_join(&other, |x: &u64, y: &u64| Ok(x + y));
        let out = joined.accumulate();
        out
    }
}

// Repetition sugar the macro recognises: `map_n`, `fan`.
wingfoil_next::graph! {
    fn surface_sugar(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let deep = count.map_n(3, |i| *i + 1);
        let fanned = deep.fan(2, |s| s.map(|i| *i * 2));
        let out = fanned.accumulate();
        out
    }
}

// Lifecycle / passthrough surface: `print` (a plain per-tick pass-through
// since deviation D8 dropped its teardown buffer) and `timed` (passes values
// through unchanged while carrying the start/stop hooks the compiled path
// emits).
wingfoil_next::graph! {
    fn surface_lifecycle(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let printed = count.print();
        let timed = printed.timed();
        let out = timed.accumulate();
        out
    }
}

// Formerly-interpreted-only surface, now dual-mode: `with_time`,
// `join_passive`, `try_join_passive`, and `delay_with_reset`. Each reaches
// `graph!`/compiled through a forwarder added alongside its op (see the module
// doc, category 3). Exercising them here — and in the `nested` parity test
// below — is exactly the two-sided guard: a dropped forwarder fails to resolve
// `__wf_op_<name>_cycle` at these call sites.
wingfoil_next::graph! {
    fn surface_passive_delay(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        // `with_time`: (NanoTime, u64) folded back to a single u64 stream. The
        // engine clock is deterministic in historical mode, so the stamped time
        // agrees across engines.
        let stamped = count
            .with_time()
            .map(|pair: &(NanoTime, u64)| u64::from(pair.0) + pair.1);
        // Two derived streams to join; `passive_src` is read passively.
        let base = count.map(|i| i * 2);
        let passive_src = count.map(|i| i * 100);
        // `join_passive` / `try_join_passive`: `base` active, `passive_src`
        // read passively (does not activate the node).
        let joined = base.join_passive(&passive_src, |x: &u64, y: &u64| x + y);
        let tried = base.try_join_passive(&passive_src, |x: &u64, y: &u64| Ok(x + y));
        // `delay_with_reset`: delay `count`, snapping to the live value whenever
        // the reset trigger (even counts) ticks.
        let flag = count.map(|i| i.is_multiple_of(2));
        let trigger = count.filter(&flag);
        let delayed = count.delay_with_reset(Duration::from_millis(25), &trigger);
        let out = joined
            .merge(&tried)
            .merge(&delayed)
            .merge(&stamped)
            .accumulate();
        out
    }
}

// --- Three-engine agreement across the surface ------------------------------
//
// Each block above compiled (proving fluent + forwarder both exist for every op
// it uses); here we also assert the interpreted and compiled engines agree on
// the values, so the completeness guard doubles as combinator-surface parity.

macro_rules! assert_interp_eq_compiled {
    ($m:ident) => {{
        let (mut runner, out) = $m::interpreted();
        runner.run(HISTORICAL, RUN).unwrap();
        let interp = runner.value(out);
        let (compiled,) = $m::compiled(HISTORICAL, RUN).unwrap();
        assert_eq!(
            interp,
            compiled,
            "interpreted vs compiled drift in {}",
            stringify!($m)
        );
        assert!(!interp.is_empty(), "{} produced no values", stringify!($m));
    }};
}

#[test]
fn u64_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_u64);
}

#[test]
fn scheduling_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_scheduling);
}

#[test]
fn windowing_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_windowing);
}

#[test]
fn multi_input_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_multi);
}

#[test]
fn time_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_time);
}

#[test]
fn fallible_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_fallible);
}

#[test]
fn sugar_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_sugar);
}

#[test]
fn lifecycle_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_lifecycle);
}

#[test]
fn passive_delay_surface_interp_eq_compiled() {
    assert_interp_eq_compiled!(surface_passive_delay);
}

/// Full three-engine agreement for the formerly-interpreted-only ops
/// (`with_time`, `join_passive`, `try_join_passive`, `delay_with_reset`):
/// `interpreted() == compiled() == nested()`. The self-contained graph is a
/// source island, so it exposes all three expansions; `nested` mounts it as one
/// node in an interpreted outer graph (following `nested_islands.rs`).
#[test]
fn passive_delay_surface_three_engine_parity() {
    let (mut runner, out) = surface_passive_delay::interpreted();
    runner.run(HISTORICAL, RUN).unwrap();
    let interp = runner.value(out);
    assert!(
        !interp.is_empty(),
        "surface_passive_delay produced no values"
    );

    let (compiled,) = surface_passive_delay::compiled(HISTORICAL, RUN).unwrap();
    assert_eq!(
        interp, compiled,
        "interpreted vs compiled drift in surface_passive_delay"
    );

    let g = GraphBuilder::new();
    let island = surface_passive_delay::nested(&g);
    let mut r = g.build();
    r.run(HISTORICAL, RUN).unwrap();
    assert_eq!(
        interp,
        r.value(&island),
        "interpreted vs nested drift in surface_passive_delay"
    );
}
