//! Op-completeness guard: protection against **one-sided op registration**,
//! adapted to the forwarder dispatch design.
//!
//! The port plan (Phase 1) called for a `supported_ops!()` list that both the
//! `graph!` parse-match and its "unsupported op" error message consume, plus a
//! test diffing that list against the fluent trait surface. That design is
//! **obsolete**: the `graph!` op *table* was deleted (see
//! `docs/macro-extensibility-decision.md`) — the macro now dispatches through
//! naming-convention forwarders (`__wf_op_<name>_*`, generated by `#[op]`), so
//! there is no central op list to diff and an unknown op simply fails to
//! resolve a forwarder at expansion time.
//!
//! The guard the plan wanted still holds, realized as a **compile-time** test.
//! A combinator *used inside* a `graph!` wiring function only compiles if it
//! has **both**:
//!   * a fluent method (the wiring fn is ordinary fluent code — a missing
//!     method is a compile error), **and**
//!   * a `graph!` forwarder (`#[op]` emits it — a missing one fails to resolve
//!     `__wf_op_<name>_cycle` / `__WF_OP_<NAME>_ACTIVATION` at the call site).
//!
//! So the `graph!` blocks below *are* the two-sided guard: every dual-mode
//! combinator is exercised here, so dropping either side (fluent method or
//! forwarder) breaks this build. Each block also asserts
//! `interpreted() == compiled()`, extending interpreted-vs-compiled parity
//! across the whole combinator surface — the biggest engine-drift surface in
//! the codebase. (`nested()` island parity is covered separately in
//! `nested_islands.rs`.)
//!
//! ## The fluent-only surface (deliberately excluded from the `graph!` blocks)
//!
//! These combinators exist fluently (and run on the interpreted engine) but are
//! **not** used in a `graph!` block above, in three categories. Adding a new op
//! means consciously placing it in a `graph!` block or in one of these lists —
//! never silently in neither.
//!
//! **1. IO / cycle — not expressible by design** (capability matrix `❌`):
//!   * `external`, `channel`, `poll` — IO / threaded / busy-poll sources; the
//!     compiled path runs its own loop with no external wake.
//!   * `feedback` (source + the `feedback` close method) — a cycle in the DAG,
//!     which straight-line compiled emission cannot express (v1 out-of-scope).
//!   * `for_each` — a fallible IO sink; lives at the runtime boundary.
//!
//! **2. Sugar over a primitive — spell the primitive in `graph!`:**
//!   * `merge_all` → a chain of 2-ary `merge`s; `not` → `map(|b| !b)`;
//!     `collapse` → `map_filter`; `split` → two `map`s. (`map_n` / `fan` are
//!     the *exception* — the macro recognises them as repetition sugar, so they
//!     ARE expressible; covered in `surface_sugar` below.)
//!
//! **3. Currently interpreted-only — candidate follow-up, not by design:**
//!   * `join_passive`, `try_join_passive` — passive-edge joins; the passive
//!     variant carries no `#[op]` forwarder yet (the active `join` / `try_join`
//!     do — covered below).
//!   * `delay_with_reset` — a hand-written builder method (no `#[op]`), so no
//!     forwarder yet.
//!   * `with_time` — a hand-written builder method (its `(NanoTime, T)` output
//!     is seeded from the input, so it dodges `T: Default` and can't be a plain
//!     `#[op]`); no forwarder yet.
//!
//! This file is the single place that classification is written down; the
//! *enforcement* is that everything in category (none) — i.e. every op meant to
//! be dual-mode — compiles in a `graph!` block.

use std::time::Duration;

use wingfoil::{NanoTime, RunFor, RunMode};
use wingfoil_next::prelude::*;

const HISTORICAL: RunMode = RunMode::HistoricalFrom(NanoTime::ZERO);
const P: Duration = Duration::from_millis(10);
const RUN: RunFor = RunFor::Cycles(12);

// The stateless / single-input `u64` surface: `count`, `map`, `map_filter`,
// `distinct`, `difference`, `limit`, `inspect`, `filter` (against a derived
// bool stream), `merge`, and `accumulate`.
wingfoil_next::graph! {
    fn surface_u64(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let mapped = count.map(|i| i * 2);
        let filtered = mapped.map_filter(|i| (*i, *i % 4 == 0));
        let distinct = filtered.distinct();
        let diff = distinct.difference();
        let limited = diff.limit(100);
        let seen = limited.inspect(|_| ());
        let is_even = count.map(|i| i.is_multiple_of(2));
        let evens = count.filter(&is_even);
        let out = seen.merge(&evens).accumulate();
        out
    }
}

// Scheduling / buffering single-input surface: `delay`, `throttle`, `window`,
// `buffer`.
wingfoil_next::graph! {
    fn surface_scheduling(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let delayed = count.delay(Duration::from_millis(25));
        let throttled = delayed.throttle(Duration::from_millis(15));
        let out = throttled.accumulate();
        out
    }
}

// Window / buffer (both emit `Vec<u64>` on a boundary).
wingfoil_next::graph! {
    fn surface_windowing(g: &GraphBuilder) -> Stream<Vec<Vec<u64>>> {
        let count = g.ticker(P).count();
        let windowed = count.window(Duration::from_millis(30));
        let buffered = count.buffer(3);
        let out = windowed.merge(&buffered).accumulate();
        out
    }
}

// Multi-input active surface: `join` and `merge`.
wingfoil_next::graph! {
    fn surface_multi(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let a = count.map(|i| i * 10);
        let b = count.map(|i| i * 100);
        // Param types annotated so inference doesn't explore unrelated blanket
        // `Add` impls (e.g. nalgebra's, pulled in under the `augurs` feature).
        let joined = a.join(&b, |x: &u64, y: &u64| x + y);
        let out = joined.merge(&a).accumulate();
        out
    }
}

// Time / passive-read surface: `ticked_at`, `ticked_at_elapsed`, `sample`.
wingfoil_next::graph! {
    fn surface_time(g: &GraphBuilder) -> Stream<Vec<NanoTime>> {
        let count = g.ticker(P).count();
        let at = count.ticked_at();
        let elapsed = count.ticked_at_elapsed();
        let flag = count.map(|i| i.is_multiple_of(2));
        let trigger = count.filter(&flag).map(|_| ());
        let gated = at.sample(&trigger);
        let out = gated.merge(&elapsed).accumulate();
        out
    }
}

// Fallible active surface: `try_map`, `try_join`.
wingfoil_next::graph! {
    fn surface_fallible(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let tried = count.try_map(|i| Ok(i + 1));
        let other = count.map(|i| i * 2);
        let joined = tried.try_join(&other, |x: &u64, y: &u64| Ok(x + y));
        let out = joined.accumulate();
        out
    }
}

// Repetition sugar the macro recognises: `map_n`, `fan`.
wingfoil_next::graph! {
    fn surface_sugar(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let deep = count.map_n(3, |i| *i + 1);
        let fanned = deep.fan(2, |s| s.map(|i| *i * 2));
        let out = fanned.accumulate();
        out
    }
}

// Lifecycle / passthrough-with-hook surface: `print`, `timed` (each passes
// values through unchanged while carrying a start/stop/teardown hook the
// compiled path now emits).
wingfoil_next::graph! {
    fn surface_lifecycle(g: &GraphBuilder) -> Stream<Vec<u64>> {
        let count = g.ticker(P).count();
        let printed = count.print();
        let timed = printed.timed();
        let out = timed.accumulate();
        out
    }
}

// --- Three-engine agreement across the surface ------------------------------
//
// Each block above compiled (proving fluent + forwarder both exist for every op
// it uses); here we also assert the interpreted and compiled engines agree on
// the values, so the completeness guard doubles as combinator-surface parity.

macro_rules! assert_interp_eq_compiled {
    ($m:ident) => {{
        let (mut runner, out) = $m::interpreted();
        runner.run(HISTORICAL, RUN).unwrap();
        let interp = runner.value(out);
        let (compiled,) = $m::compiled(HISTORICAL, RUN).unwrap();
        assert_eq!(
            interp,
            compiled,
            "interpreted vs compiled drift in {}",
            stringify!($m)
        );
        assert!(!interp.is_empty(), "{} produced no values", stringify!($m));
    }};
}

#[test]
fn u64_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_u64);
}

#[test]
fn scheduling_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_scheduling);
}

#[test]
fn windowing_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_windowing);
}

#[test]
fn multi_input_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_multi);
}

#[test]
fn time_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_time);
}

#[test]
fn fallible_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_fallible);
}

#[test]
fn sugar_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_sugar);
}

#[test]
fn lifecycle_surface_three_engine_parity() {
    assert_interp_eq_compiled!(surface_lifecycle);
}
