//! Ahead-of-time code generation: compile a wired graph's schedule to Rust.
//!
//! [`generate`] walks a wired graph and emits a standalone Rust source file
//! containing a *static schedule*: the dispatch order, tick propagation and
//! active edges are compiled into straight-line code instead of being
//! interpreted by the engine's dirty-list/layer machinery at runtime. Node
//! behaviour (including closures captured by `map`, `filter`, etc.) stays in
//! your wiring code — the generated `run` function takes the same root nodes
//! that [`Graph`](crate::Graph) would and re-wires them deterministically.
//!
//! What is compiled away: per-cycle layer vectors, dirty-node lists,
//! downstream edge iteration and node-index hashing. What remains at runtime
//! is [`StaticRuntime`], a thin shim over the engine's clock/callback
//! management (scheduled callbacks, ready callbacks from threaded sources,
//! lifecycle and error contexts) which shares its implementation with the
//! interpreted engine so the two cannot drift semantically.
//!
//! # Workflow
//!
//! ```
//! use std::time::Duration;
//! use wingfoil::*;
//!
//! // Your wiring function, unchanged.
//! fn wire() -> std::rc::Rc<dyn Node> {
//!     ticker(Duration::from_millis(10)).count().print().as_node()
//! }
//!
//! // One-off (a small bin, example, or build step): emit the static runner.
//! let source = wingfoil::codegen::generate(vec![wire()], &Default::default()).unwrap();
//! assert!(source.starts_with("// @generated by wingfoil::codegen"));
//! // std::fs::write("src/generated.rs", source)?;
//!
//! // In the application, the generated file replaces Graph::run:
//! //     mod generated;
//! //     generated::run(vec![wire()], RunMode::RealTime, RunFor::Forever)?;
//! ```
//!
//! The generated `run` guards against wiring drift: it re-derives a
//! fingerprint of the topology (node types, edges, active flags) and fails
//! with a "regenerate" error if it no longer matches the compiled schedule.
//!
//! # Two generators
//!
//! - [`generate`] (this page) — compiles the *schedule*. Core node kinds
//!   (`map`, `filter`, `fold`, `constant`, `sample`, `merge`) are executed
//!   through typed handles with static dispatch (`inline: true`, the
//!   default); every other node falls back to dynamic dispatch. Works with
//!   **any** graph, and node state stays in the wired nodes (so `peek_value`
//!   handles keep working after the run).
//! - [`generate_standalone`] — compiles the *whole graph*: no executor, no
//!   nodes, state in monomorphized locals, and the user's closures supplied
//!   via a generated `Inputs` struct so the compiler inlines their bodies
//!   into the schedule. Restricted to the core node kinds above plus
//!   `ticker`; see [`standalone`](self) module docs for details.
//!
//! # Limitations
//!
//! - Dynamic graph changes (`add_upstream` / `remove_node`, behind the
//!   `dynamic-graph` feature) are rejected at runtime — a compiled schedule
//!   cannot change shape. Use the interpreted engine for those graphs.
//! - The wiring function must produce the same topology as at generation
//!   time; the fingerprint guard turns a mismatch into an error at startup.
//! - Each cycle evaluates one dispatch line per node. Quiet nodes cost only
//!   a predicted register test (`dirty` checks are emitted solely for node
//!   kinds that can actually receive callbacks), but the floor is still
//!   O(nodes) per cycle — whereas the interpreted engine's dirty-lists do
//!   work proportional to *ticking* nodes only. Static runners target
//!   small-to-medium hot graphs; for very large, sparsely-ticking graphs
//!   measure both engines.

mod kernel;
mod standalone;

pub use kernel::Kernel;
pub use standalone::generate_standalone;

use std::cell::RefCell;
use std::fmt::Write as _;
use std::rc::Rc;

use crate::graph::{Graph, RunBounds, first_error};
use crate::types::{MutableNode, NanoTime, Node};
use crate::{RunFor, RunMode};

/// Result alias used by generated code, so consuming crates don't need a
/// direct `anyhow` dependency.
pub type Result<T> = anyhow::Result<T>;

/// Options for [`generate`].
#[derive(Debug, Clone)]
pub struct CodegenOptions {
    /// Name of the generated entry-point function. Default: `"run"`.
    pub function_name: String,
    /// Statically dispatch core node kinds via typed downcast handles instead
    /// of dynamic `cycle_node` calls, when their value types are nameable in
    /// generated source. Stateless kinds (`map`, `filter`, `fold`,
    /// `constant`, `sample`, `merge`) go through `cycle_inline` (no
    /// `GraphState`); state-needing kinds (`ticker`, `delay`,
    /// `delay_with_reset`, `throttle`, `print`) go through `cycle_typed`
    /// (concrete `cycle` with the real `GraphState`). Other nodes (and
    /// non-nameable types) fall back to dynamic dispatch. Default: `true`.
    pub inline: bool,
}

impl Default for CodegenOptions {
    fn default() -> Self {
        Self {
            function_name: "run".to_string(),
            inline: true,
        }
    }
}

/// Node kinds the generators understand structurally. `Opaque` nodes are
/// driven through dynamic dispatch ([`StaticRuntime::cycle_node`]) by
/// [`generate`], and rejected by [`generate_standalone`].
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum NodeKind {
    Tick,
    Constant,
    Sample,
    Map,
    Filter,
    Fold,
    Merge,
    Opaque,
}

/// Structural facts about one wired node, shared by both generators.
pub(crate) struct NodeInfo {
    pub(crate) kind: NodeKind,
    /// Sanitized type name, e.g. `MapStream`.
    pub(crate) short: String,
    /// Generic argument source strings, e.g. `["u64", "bool"]`.
    pub(crate) generics: Vec<String>,
    pub(crate) actives: Vec<usize>,
    pub(crate) passives: Vec<usize>,
    pub(crate) has_active_downstream: bool,
}

impl NodeInfo {
    /// Full source path for a typed downcast handle (`wingfoil::MapStream<u64,
    /// bool>`), if this node's kind is inlinable and every generic argument is
    /// nameable in generated source.
    fn inline_type(&self) -> Option<String> {
        match self.kind {
            NodeKind::Map
            | NodeKind::Filter
            | NodeKind::Fold
            | NodeKind::Constant
            | NodeKind::Sample
            | NodeKind::Merge => {}
            NodeKind::Tick | NodeKind::Opaque => return None,
        }
        if !self.generics.iter().all(|g| type_is_nameable(g)) {
            return None;
        }
        Some(format!(
            "wingfoil::{}<{}>",
            self.short,
            self.generics.join(", ")
        ))
    }

    /// Full source path for a typed handle used with
    /// [`StaticRuntime::cycle_typed`]: state-needing kinds whose `cycle` is
    /// dispatched statically on the concrete type (the trait method stays the
    /// single source of truth — the handle just bypasses the `dyn Node`
    /// vtable). `None` when the kind is not in the typed-dispatch set or a
    /// generic argument is not nameable.
    fn typed_dispatch_type(&self) -> Option<String> {
        const TYPED: &[&str] = &[
            "TickNode",
            "DelayStream",
            "DelayWithResetStream",
            "ThrottleStream",
            "PrintStream",
        ];
        if !TYPED.contains(&self.short.as_str()) {
            return None;
        }
        if !self.generics.iter().all(|g| type_is_nameable(g)) {
            return None;
        }
        if self.generics.is_empty() {
            Some(format!("wingfoil::{}", self.short))
        } else {
            Some(format!(
                "wingfoil::{}<{}>",
                self.short,
                self.generics.join(", ")
            ))
        }
    }
}

/// How the generated schedule executes one node.
enum DispatchTier {
    /// Stateless static dispatch through `cycle_inline` (no `GraphState`).
    Inline(String),
    /// Static dispatch of the trait `cycle` on the concrete type, with the
    /// real `GraphState` (delay, ticker, throttle, ...).
    Typed(String),
    /// Dynamic dispatch through `StaticRuntime::cycle_node`.
    Dynamic,
}

/// True if a node of this type can be activated by callback processing —
/// i.e. its dispatch condition needs a `dirty` check in addition to upstream
/// tick propagation.
///
/// Callback activation is always self-inflicted: `add_callback` /
/// `always_callback` / `ReadyNotifier` bind to the *calling* node's index,
/// and a feedback sink targets its own paired stream. So a node type that
/// never registers callbacks can never be marked dirty, and its `dirty` term
/// is statically dead — the generators drop it, keeping quiet subgraphs on
/// pure register logic. Unknown kinds conservatively return `true`.
pub(crate) fn can_receive_callbacks(short: &str) -> bool {
    // These kinds never call add_callback/always_callback/ready_notifier —
    // neither in cycle() nor in any lifecycle hook.
    const CALLBACK_FREE: &[&str] = &[
        "MapStream",
        "FilterStream",
        "FoldStream",
        "SampleStream",
        "MergeStream",
        "ThrottleStream",
        "PrintStream",
    ];
    !CALLBACK_FREE.contains(&short)
}

pub(crate) fn classify(short: &str) -> NodeKind {
    match short {
        "TickNode" => NodeKind::Tick,
        "ConstantStream" => NodeKind::Constant,
        "SampleStream" => NodeKind::Sample,
        "MapStream" => NodeKind::Map,
        "FilterStream" => NodeKind::Filter,
        "FoldStream" => NodeKind::Fold,
        "MergeStream" => NodeKind::Merge,
        _ => NodeKind::Opaque,
    }
}

/// Split `MapStream<u64, Vec<String>>` into (`MapStream`, `["u64",
/// "Vec<String>"]`), honouring nested generics.
pub(crate) fn split_generics(full: &str) -> (&str, Vec<String>) {
    let Some(open) = full.find('<') else {
        return (full.trim(), Vec::new());
    };
    let name = full[..open].trim();
    let Some(inner) = full[open + 1..].strip_suffix('>') else {
        return (name, Vec::new());
    };
    let mut args = Vec::new();
    let mut depth = 0usize;
    let mut start = 0usize;
    for (i, c) in inner.char_indices() {
        match c {
            '<' | '(' | '[' => depth += 1,
            '>' | ')' | ']' => depth = depth.saturating_sub(1),
            ',' if depth == 0 => {
                args.push(inner[start..i].trim().to_string());
                start = i + 1;
            }
            _ => {}
        }
    }
    if start < inner.len() {
        args.push(inner[start..].trim().to_string());
    }
    (name, args)
}

/// Conservative check that a sanitized type string resolves in generated
/// source: every identifier must be a primitive, a prelude type, or a
/// wingfoil export the generated file imports. User-defined types (whose
/// paths were stripped by `tynm`) fail this check and force dynamic-dispatch
/// fallback rather than emitting unresolvable source.
pub(crate) fn type_is_nameable(ty: &str) -> bool {
    const ALLOWED: &[&str] = &[
        "u8", "u16", "u32", "u64", "u128", "usize", "i8", "i16", "i32", "i64", "i128", "isize",
        "f32", "f64", "bool", "char", "String", "Vec", "Option", "NanoTime", "ValueAt",
    ];
    if ty.trim().is_empty() {
        return false;
    }
    let mut ident = String::new();
    for c in ty.chars().chain(std::iter::once(' ')) {
        if c.is_alphanumeric() || c == '_' {
            ident.push(c);
            continue;
        }
        if !ident.is_empty() {
            if !ALLOWED.contains(&ident.as_str()) {
                return false;
            }
            ident.clear();
        }
        match c {
            '<' | '>' | ',' | '(' | ')' | ' ' => {}
            _ => return false,
        }
    }
    true
}

/// Gather structural info for every node of a wired graph.
pub(crate) fn node_infos(graph: &Graph) -> Vec<NodeInfo> {
    let n = graph.node_count();
    let mut infos: Vec<NodeInfo> = (0..n)
        .map(|i| {
            let full = graph.node_type_name(i);
            let (short, generics) = split_generics(&full);
            NodeInfo {
                kind: classify(short),
                short: short.to_string(),
                generics,
                actives: graph.active_upstream_indices(i),
                passives: graph.passive_upstream_indices(i),
                has_active_downstream: false,
            }
        })
        .collect();
    for i in 0..n {
        for u in infos[i].actives.clone() {
            infos[u].has_active_downstream = true;
        }
    }
    infos
}

/// The runtime shim driven by generated static runners.
///
/// Owns a fully wired [`Graph`] and exposes the engine's run-loop primitives
/// (`begin_cycle` / `cycle_node` / `end_cycle` / lifecycle) without the
/// interpreted scheduler: tick propagation is the generated caller's job.
/// All time and callback semantics are shared with [`Graph::run`], so a graph
/// produces identical results under both engines.
pub struct StaticRuntime {
    graph: Graph,
    bounds: Option<RunBounds>,
    is_realtime: bool,
    cycles: u32,
}

impl StaticRuntime {
    /// Wire `roots` (exactly as [`Graph::new`] would) and prepare a static
    /// run. Surfaces wiring errors (e.g. a cycle) immediately.
    pub fn new(roots: Vec<Rc<dyn Node>>, run_mode: RunMode, run_for: RunFor) -> Result<Self> {
        let mut graph = Graph::new(roots, run_mode, run_for);
        if let Some(e) = graph.take_wiring_error() {
            return Err(e);
        }
        Ok(Self {
            graph,
            bounds: None,
            is_realtime: matches!(run_mode, RunMode::RealTime),
            cycles: 0,
        })
    }

    /// Number of nodes in the wired graph.
    pub fn node_count(&self) -> usize {
        self.graph.node_count()
    }

    /// Verify the wired topology still matches the one the calling schedule
    /// was generated from. Generated runners call this before [`run`](Self::run).
    pub fn check_topology(&self, expected_nodes: usize, expected_fingerprint: u64) -> Result<()> {
        let actual_nodes = self.graph.node_count();
        let actual_fingerprint = fingerprint(&self.graph);
        if actual_nodes != expected_nodes || actual_fingerprint != expected_fingerprint {
            anyhow::bail!(
                "graph topology does not match this generated static runner: expected \
                 {expected_nodes} nodes with fingerprint {expected_fingerprint:#018x}, wired \
                 {actual_nodes} nodes with fingerprint {actual_fingerprint:#018x}. The wiring has \
                 changed since the runner was generated — regenerate it with \
                 wingfoil::codegen::generate. Wired topology:\n{}",
                topology_table(&self.graph)
            );
        }
        Ok(())
    }

    /// Execute a full run with `run_cycles` as the schedule: the generated
    /// `*_cycles` function (or any closure driving `begin_cycle` /
    /// `cycle_node` / `end_cycle`).
    ///
    /// Owns the whole lifecycle with the same guarantees as [`Graph::run`]:
    /// once `start` is attempted, `stop` and `teardown` always run — even if
    /// `start` or the run loop errors — and the first failure in lifecycle
    /// order is primary with later ones attached.
    pub fn run(&mut self, run_cycles: impl FnOnce(&mut StaticRuntime) -> Result<()>) -> Result<()> {
        self.graph.setup_nodes()?;
        let start_result = self.graph.start_nodes();
        // Skip the run loop if any node failed to start, but still stop and
        // tear down so partially-started nodes get cleaned up.
        let run_result = if start_result.is_ok() {
            run_cycles(self)
        } else {
            Ok(())
        };
        let stop_result = self.graph.stop_nodes();
        let teardown_result = self.graph.teardown_nodes();
        first_error([start_result, run_result, stop_result, teardown_result])
    }

    /// Advance to the next cycle: process due callbacks (marking their nodes
    /// dirty) and advance engine time. Returns `Ok(false)` when the run is
    /// complete. Identical semantics to the interpreted engine's loop head.
    pub fn begin_cycle(&mut self) -> Result<bool> {
        if self.bounds.is_none() {
            self.bounds = Some(self.graph.begin_run());
        }
        let bounds = self.bounds.expect("bounds initialised above");
        self.graph.advance(self.cycles, &bounds, self.is_realtime)
    }

    /// True if `index` was marked dirty by callback processing this cycle
    /// (scheduled callbacks, always-callbacks, or ready callbacks from
    /// threaded sources).
    pub fn is_dirty(&self, index: usize) -> bool {
        self.graph.is_node_dirty(index)
    }

    /// Cycle one node and return whether it ticked. Does **not** propagate
    /// the tick — the generated schedule does that statically.
    pub fn cycle_node(&mut self, index: usize) -> Result<bool> {
        self.graph.cycle_node_inner(index)
    }

    /// Obtain a typed handle to node `index` for static dispatch (the
    /// `cycle_inline` fast path in generated runners). Fails with a
    /// "regenerate" error if the wired node is not the expected concrete type.
    pub fn typed<T: MutableNode + 'static>(&self, index: usize) -> Result<Rc<RefCell<T>>> {
        let node = self.graph.node_rc(index);
        let wired = node.type_name();
        node.as_any_rc().downcast::<RefCell<T>>().map_err(|_| {
            anyhow::anyhow!(
                "generated static runner expected node [{index}] to be `{}` but the wired graph \
                 has `{wired}` — the wiring has changed since the runner was generated; \
                 regenerate it with wingfoil::codegen::generate",
                tynm::type_name::<T>(),
            )
        })
    }

    /// Cycle a state-needing node through its typed handle: identical engine
    /// bookkeeping to [`cycle_node`](Self::cycle_node) (current-node index so
    /// `add_callback` works, tick recording, error context), but the `cycle`
    /// call is dispatched statically on the concrete type instead of through
    /// the `dyn Node` vtable.
    pub fn cycle_typed<T: MutableNode + 'static>(
        &mut self,
        index: usize,
        node: &Rc<RefCell<T>>,
    ) -> Result<bool> {
        self.graph.cycle_typed_inner(index, node)
    }

    /// Record the tick outcome of a statically-dispatched (inlined) node on
    /// the graph state — keeping [`GraphState::ticked`] correct for fallback
    /// nodes that consult it — and pass the outcome through.
    ///
    /// [`GraphState::ticked`]: crate::GraphState::ticked
    pub fn did_tick(&mut self, index: usize, ticked: bool) -> bool {
        if ticked {
            self.graph.set_node_ticked(index);
        }
        ticked
    }

    /// Finish the current cycle: clear per-cycle tick/dirty state.
    ///
    /// Errors if a node requested a dynamic graph change during the cycle —
    /// a compiled schedule cannot change shape.
    pub fn end_cycle(&mut self) -> Result<()> {
        #[cfg(feature = "dynamic-graph")]
        if self.graph.has_pending_dynamic_changes() {
            anyhow::bail!(
                "dynamic graph changes (add_upstream/remove_node) are not supported by a \
                 generated static runner; run this graph with the interpreted engine \
                 (Graph::run) instead"
            );
        }
        self.graph.reset();
        self.cycles += 1;
        Ok(())
    }
}

/// Strip generic parameters from a type name: `MapStream<u64, bool>` →
/// `MapStream`. Keeps generated output stable across compiler versions
/// (closure type names inside generics are compiler-dependent).
fn short_type_name(full: &str) -> &str {
    full.split('<').next().unwrap_or(full).trim()
}

/// FNV-1a hash of the wired topology: sanitized node type names plus active
/// and passive upstream index lists. Computed identically at generation time
/// (baked into the emitted `check_topology` call) and at runtime.
fn fingerprint(graph: &Graph) -> u64 {
    const OFFSET: u64 = 0xcbf2_9ce4_8422_2325;
    const PRIME: u64 = 0x0000_0100_0000_01b3;
    let mut canonical = String::new();
    for i in 0..graph.node_count() {
        let name = graph.node_type_name(i);
        canonical.push_str(&format!(
            "{i}|{}|a{:?}|p{:?}\n",
            short_type_name(&name),
            graph.active_upstream_indices(i),
            graph.passive_upstream_indices(i),
        ));
    }
    let mut hash = OFFSET;
    for byte in canonical.bytes() {
        hash ^= byte as u64;
        hash = hash.wrapping_mul(PRIME);
    }
    hash
}

/// Human-readable topology table: one line per node with layer, sanitized
/// type name and upstream edges. Used in the generated file header and in
/// `check_topology` mismatch errors.
fn topology_table(graph: &Graph) -> String {
    let names: Vec<String> = (0..graph.node_count())
        .map(|i| short_type_name(&graph.node_type_name(i)).to_string())
        .collect();
    let name_width = names.iter().map(String::len).max().unwrap_or(0);
    let mut out = String::new();
    out.push_str(&format!(
        "index  layer  {:name_width$}  active upstreams\n",
        "node"
    ));
    for (i, name) in names.iter().enumerate() {
        let actives = graph.active_upstream_indices(i);
        let passives = graph.passive_upstream_indices(i);
        let mut edges = if actives.is_empty() && passives.is_empty() {
            "(source)".to_string()
        } else {
            format!("{actives:?}")
        };
        if !passives.is_empty() {
            edges.push_str(&format!(" (passive: {passives:?})"));
        }
        out.push_str(&format!(
            "[{i:02}]   {:<5}  {name:name_width$}  {edges}\n",
            graph.node_layer(i),
        ));
    }
    out
}

/// Generate a standalone Rust source file containing a static runner for the
/// graph reachable from `roots`.
///
/// The emitted file exposes `pub fn <function_name>(roots, run_mode, run_for)`
/// with the same behaviour as wiring `roots` into a [`Graph`] and calling
/// [`Graph::run`], but with the schedule compiled to straight-line code. Write
/// it into your crate (e.g. `src/generated.rs`), declare it as a module, and
/// call it with root nodes produced by the *same wiring code* used here.
pub fn generate(roots: Vec<Rc<dyn Node>>, options: &CodegenOptions) -> Result<String> {
    // Run mode / bounds are irrelevant for wiring; use inert values.
    let mut graph = Graph::new(
        roots,
        RunMode::HistoricalFrom(NanoTime::ZERO),
        RunFor::Forever,
    );
    if let Some(e) = graph.take_wiring_error() {
        return Err(e);
    }
    let n = graph.node_count();
    let fp = fingerprint(&graph);
    let fn_name = &options.function_name;

    let infos = node_infos(&graph);
    let tiers: Vec<DispatchTier> = infos
        .iter()
        .map(|info| {
            if !options.inline {
                return DispatchTier::Dynamic;
            }
            if let Some(ty) = info.inline_type() {
                DispatchTier::Inline(ty)
            } else if let Some(ty) = info.typed_dispatch_type() {
                DispatchTier::Typed(ty)
            } else {
                DispatchTier::Dynamic
            }
        })
        .collect();
    let handle_types: Vec<Option<&String>> = tiers
        .iter()
        .map(|tier| match tier {
            DispatchTier::Inline(ty) | DispatchTier::Typed(ty) => Some(ty),
            DispatchTier::Dynamic => None,
        })
        .collect();
    let any_inline = handle_types.iter().any(Option::is_some);

    let mut out = String::new();
    let w = &mut out;
    writeln!(w, "// @generated by wingfoil::codegen. DO NOT EDIT.")?;
    writeln!(w, "//")?;
    writeln!(
        w,
        "// Static runner for a wingfoil graph with {n} nodes. Rebuild the same graph"
    )?;
    writeln!(
        w,
        "// and pass its root nodes to `{fn_name}`; the schedule below is specialised to"
    )?;
    writeln!(
        w,
        "// this exact topology. If the wiring changes, regenerate this file."
    )?;
    writeln!(w, "//")?;
    for line in topology_table(&graph).lines() {
        writeln!(w, "// {line}")?;
    }
    writeln!(w)?;
    if any_inline {
        writeln!(w, "use std::cell::RefCell;")?;
    }
    writeln!(w, "use std::rc::Rc;")?;
    writeln!(w, "use wingfoil::codegen::StaticRuntime;")?;
    let inline_source: String = handle_types.iter().flatten().map(|s| s.as_str()).collect();
    let mut wingfoil_imports = vec!["Node", "RunFor", "RunMode"];
    for extra in ["NanoTime", "ValueAt"] {
        if inline_source.contains(extra) {
            wingfoil_imports.push(extra);
        }
    }
    wingfoil_imports.sort_unstable();
    writeln!(w, "use wingfoil::{{{}}};", wingfoil_imports.join(", "))?;
    writeln!(w)?;
    writeln!(
        w,
        "/// Runs the graph rooted at `roots` using the statically compiled schedule below."
    )?;
    writeln!(w, "#[rustfmt::skip]")?;
    writeln!(w, "pub fn {fn_name}(")?;
    writeln!(w, "    roots: Vec<Rc<dyn Node>>,")?;
    writeln!(w, "    run_mode: RunMode,")?;
    writeln!(w, "    run_for: RunFor,")?;
    writeln!(w, ") -> wingfoil::codegen::Result<()> {{")?;
    writeln!(
        w,
        "    let mut rt = StaticRuntime::new(roots, run_mode, run_for)?;"
    )?;
    writeln!(w, "    rt.check_topology({n}, {fp:#018x})?;")?;

    // One dispatch line per node, in wiring (topological) order. Ticks
    // propagate through `ticked_*` locals along active edges; `is_dirty`
    // covers callback-driven activation (tickers, delay, feedback, threaded
    // sources). Passive edges generate nothing. Stateless kinds go through a
    // typed handle's `cycle_inline` (no GraphState); state-needing kinds in
    // the typed-dispatch set go through `cycle_typed` (real GraphState,
    // concrete `cycle`); everything else falls back to dynamic dispatch via
    // `cycle_node`.
    let mut lines: Vec<(String, String)> = Vec::with_capacity(n);
    for (i, info) in infos.iter().enumerate() {
        let mut cond_parts: Vec<String> =
            info.actives.iter().map(|u| format!("ticked_{u}")).collect();
        // The dirty check only exists for callback activation; drop it when
        // the node type provably never registers callbacks, so quiet
        // subgraphs stay on register-only logic.
        if can_receive_callbacks(&info.short) {
            cond_parts.push(format!("rt.is_dirty({i})"));
        }
        let call = match &tiers[i] {
            DispatchTier::Inline(_) => {
                let call = if info.kind == NodeKind::Merge {
                    let flags: Vec<String> =
                        info.actives.iter().map(|u| format!("ticked_{u}")).collect();
                    format!("n{i}.borrow_mut().cycle_inline(&[{}])", flags.join(", "))
                } else {
                    format!("n{i}.borrow_mut().cycle_inline()")
                };
                format!("rt.did_tick({i}, {call})")
            }
            DispatchTier::Typed(_) => format!("rt.cycle_typed({i}, &n{i})?"),
            DispatchTier::Dynamic => format!("rt.cycle_node({i})?"),
        };
        let cond = cond_parts.join(" || ");
        let code = if cond_parts.is_empty() {
            // No activation source at all: the node can never tick.
            if info.has_active_downstream {
                format!("let ticked_{i} = false;")
            } else {
                continue;
            }
        } else if info.has_active_downstream {
            if cond_parts.len() > 1 {
                format!("let ticked_{i} = ({cond}) && {call};")
            } else {
                format!("let ticked_{i} = {cond} && {call};")
            }
        } else {
            format!("if {cond} {{ {call}; }}")
        };
        lines.push((code, format!("// [{i:02}] {}", info.short)));
    }
    let code_width = lines.iter().map(|(code, _)| code.len()).max().unwrap_or(0);

    if any_inline {
        // Typed handles + the schedule as a closure so the handles stay in scope.
        for (i, ty) in handle_types.iter().enumerate() {
            if let Some(ty) = ty {
                writeln!(w, "    let n{i}: Rc<RefCell<{ty}>> = rt.typed({i})?;")?;
            }
        }
        writeln!(w, "    rt.run(|rt| {{")?;
        writeln!(w, "        while rt.begin_cycle()? {{")?;
        for (code, comment) in &lines {
            writeln!(w, "            {code:code_width$}  {comment}")?;
        }
        writeln!(w, "            rt.end_cycle()?;")?;
        writeln!(w, "        }}")?;
        writeln!(w, "        Ok(())")?;
        writeln!(w, "    }})")?;
        writeln!(w, "}}")?;
    } else {
        writeln!(w, "    rt.run({fn_name}_cycles)")?;
        writeln!(w, "}}")?;
        writeln!(w)?;
        writeln!(w, "#[rustfmt::skip]")?;
        writeln!(
            w,
            "fn {fn_name}_cycles(rt: &mut StaticRuntime) -> wingfoil::codegen::Result<()> {{"
        )?;
        writeln!(w, "    while rt.begin_cycle()? {{")?;
        for (code, comment) in &lines {
            writeln!(w, "        {code:code_width$}  {comment}")?;
        }
        writeln!(w, "        rt.end_cycle()?;")?;
        writeln!(w, "    }}")?;
        writeln!(w, "    Ok(())")?;
        writeln!(w, "}}")?;
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ValueAt;
    use crate::nodes::*;
    use crate::types::*;
    use std::time::Duration;

    /// Drive a `StaticRuntime` exactly the way generated code does, but with
    /// the schedule interpreted from the wired topology instead of unrolled.
    /// This exercises the runtime shim's semantics for arbitrary graphs.
    fn drive_static(
        roots: Vec<Rc<dyn Node>>,
        run_mode: RunMode,
        run_for: RunFor,
    ) -> anyhow::Result<()> {
        let probe = Graph::new(roots.clone(), run_mode, run_for);
        let n = probe.node_count();
        let ups: Vec<Vec<usize>> = (0..n).map(|i| probe.active_upstream_indices(i)).collect();
        drop(probe);

        let mut rt = StaticRuntime::new(roots, run_mode, run_for)?;
        rt.run(|rt| {
            let mut ticked = vec![false; n];
            while rt.begin_cycle()? {
                for i in 0..n {
                    let due = rt.is_dirty(i) || ups[i].iter().any(|&u| ticked[u]);
                    ticked[i] = due && rt.cycle_node(i)?;
                }
                rt.end_cycle()?;
            }
            Ok(())
        })
    }

    /// Delay where the delay (100ns) far exceeds the tick period (10ns), so
    /// most delayed emissions happen on cycles where the delay node's
    /// upstream did NOT tick — activation comes purely from its scheduled
    /// callback (`is_dirty`), the interesting path for a static schedule.
    fn wire_delay() -> (Vec<Rc<dyn Node>>, Rc<dyn Stream<Vec<ValueAt<u64>>>>) {
        let delayed = ticker(Duration::from_nanos(10))
            .count()
            .delay(Duration::from_nanos(100))
            .collect();
        (vec![delayed.clone().as_node()], delayed)
    }

    #[test]
    fn static_runtime_matches_interpreted_delay() {
        let run_mode = RunMode::HistoricalFrom(NanoTime::ZERO);
        let run_for = RunFor::Duration(Duration::from_nanos(120));

        let (roots, values) = wire_delay();
        Graph::new(roots, run_mode, run_for).run().unwrap();
        let expected = values.peek_value();
        // Sanity-check against the known behaviour (see delay.rs tests): the
        // first delayed value lands at t=100 despite sourcing from t=0.
        assert_eq!(1, expected[0].value);
        assert_eq!(NanoTime::new(100), expected[0].time);
        assert!(expected.len() >= 4);

        let (roots, values) = wire_delay();
        drive_static(roots, run_mode, run_for).unwrap();
        assert_eq!(expected, values.peek_value());
    }

    /// Passive read of a delayed stream (`delay_initializes_to_first_value`
    /// from delay.rs, run through the static runtime).
    #[test]
    fn static_runtime_matches_interpreted_delay_passive() {
        fn wire() -> (Vec<Rc<dyn Node>>, Rc<dyn Stream<Vec<i64>>>) {
            let source = ticker(Duration::from_secs(1)).count().map(|x| x as i64 + 4);
            let delayed = source.delay(Duration::from_secs(5));
            let diff = bimap(Dep::Active(source), Dep::Passive(delayed), |a, b| a - b);
            let acc = diff.accumulate();
            (vec![acc.clone().as_node()], acc)
        }
        let run_mode = RunMode::HistoricalFrom(NanoTime::ZERO);
        let run_for = RunFor::Duration(Duration::from_secs(8));

        let (roots, values) = wire();
        Graph::new(roots, run_mode, run_for).run().unwrap();
        let expected = values.peek_value();
        assert_eq!(vec![0, 1, 2, 3, 4, 5, 5, 5, 5, 5], expected);

        let (roots, values) = wire();
        drive_static(roots, run_mode, run_for).unwrap();
        assert_eq!(expected, values.peek_value());
    }

    fn wire_pipeline() -> (Rc<dyn Node>, Rc<dyn Stream<Vec<u64>>>) {
        let source = ticker(Duration::from_nanos(100)).count();
        let evens = source.clone().filter(source.map(|i| i % 2 == 0));
        let acc = evens.map(|i| i * 10).accumulate();
        (acc.clone().as_node(), acc)
    }

    #[test]
    fn static_runtime_matches_interpreted_pipeline() {
        let (root, values) = wire_pipeline();
        root.run(RunMode::HistoricalFrom(NanoTime::ZERO), RunFor::Cycles(10))
            .unwrap();
        let expected = values.peek_value();
        assert!(!expected.is_empty());

        let (root, values) = wire_pipeline();
        drive_static(
            vec![root],
            RunMode::HistoricalFrom(NanoTime::ZERO),
            RunFor::Cycles(10),
        )
        .unwrap();
        assert_eq!(expected, values.peek_value());
    }

    fn wire_feedback() -> (Vec<Rc<dyn Node>>, Rc<dyn Stream<Vec<u64>>>) {
        let (tx, rx) = feedback::<u64>();
        let source = ticker(Duration::from_nanos(100)).count();
        let value = bimap(
            crate::Dep::Active(source),
            crate::Dep::Passive(rx),
            |src, fb| src + fb * 10,
        );
        let fb = value.feedback(tx);
        let acc = value.accumulate();
        (vec![fb.as_node(), acc.clone().as_node()], acc)
    }

    #[test]
    fn static_runtime_matches_interpreted_feedback() {
        let (roots, values) = wire_feedback();
        Graph::new(
            roots,
            RunMode::HistoricalFrom(NanoTime::ZERO),
            RunFor::Duration(Duration::from_nanos(500)),
        )
        .run()
        .unwrap();
        let expected = values.peek_value();
        assert_eq!(vec![1, 12, 123, 1234, 12345, 123456], expected);

        let (roots, values) = wire_feedback();
        drive_static(
            roots,
            RunMode::HistoricalFrom(NanoTime::ZERO),
            RunFor::Duration(Duration::from_nanos(500)),
        )
        .unwrap();
        assert_eq!(expected, values.peek_value());
    }

    #[test]
    fn static_runtime_works_in_realtime() {
        let source = ticker(Duration::from_millis(1)).count();
        drive_static(
            vec![source.clone().as_node()],
            RunMode::RealTime,
            RunFor::Cycles(3),
        )
        .unwrap();
        assert_eq!(3, source.peek_value());
    }

    #[test]
    fn generate_is_deterministic() {
        let (root, _) = wire_pipeline();
        let a = generate(vec![root], &CodegenOptions::default()).unwrap();
        let (root, _) = wire_pipeline();
        let b = generate(vec![root], &CodegenOptions::default()).unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn generate_emits_expected_shape() {
        let (root, _) = wire_pipeline();
        let src = generate(vec![root], &CodegenOptions::default()).unwrap();
        assert!(src.starts_with("// @generated by wingfoil::codegen"));
        assert!(src.contains("pub fn run("));
        assert!(src.contains("rt.check_topology("));
        assert!(src.contains("while rt.begin_cycle()? {"));
        assert!(src.contains("rt.end_cycle()?;"));
        // Sources have no propagation inputs; the ticker is typed-dispatched.
        assert!(src.contains("let ticked_0 = rt.is_dirty(0) && rt.cycle_typed(0, &n0)?;"));
        // Dynamic-dispatch mode keeps everything on cycle_node.
        let (root, _) = wire_pipeline();
        let opts = CodegenOptions {
            inline: false,
            ..Default::default()
        };
        let src = generate(vec![root], &opts).unwrap();
        assert!(src.contains("let ticked_0 = rt.is_dirty(0) && rt.cycle_node(0)?;"));
    }

    #[test]
    fn callback_free_nodes_have_no_dirty_check() {
        // wire_pipeline: [0] TickNode, [1] ConstantStream, then sample /
        // fold / map / filter / map / fold — all callback-free. Only the two
        // schedulable sources may carry a dirty check.
        let (root, _) = wire_pipeline();
        let src = generate(vec![root], &CodegenOptions::default()).unwrap();
        assert!(src.contains("rt.is_dirty(0)"));
        assert!(src.contains("rt.is_dirty(1)"));
        assert_eq!(
            2,
            src.matches("rt.is_dirty").count(),
            "callback-free nodes must not emit dirty checks:\n{src}"
        );
    }

    #[test]
    fn generate_honours_function_name() {
        let (root, _) = wire_pipeline();
        let opts = CodegenOptions {
            function_name: "run_pricing".to_string(),
            ..Default::default()
        };
        let src = generate(vec![root], &opts).unwrap();
        // Inline mode (the default) keeps the whole schedule in one function.
        assert!(src.contains("pub fn run_pricing("));

        let (root, _) = wire_pipeline();
        let opts = CodegenOptions {
            function_name: "run_pricing".to_string(),
            inline: false,
        };
        let src = generate(vec![root], &opts).unwrap();
        assert!(src.contains("pub fn run_pricing("));
        assert!(src.contains("fn run_pricing_cycles("));
    }

    #[test]
    fn check_topology_rejects_different_graph() {
        let (root, _) = wire_pipeline();
        let rt = StaticRuntime::new(
            vec![root],
            RunMode::HistoricalFrom(NanoTime::ZERO),
            RunFor::Cycles(1),
        )
        .unwrap();
        let n = rt.node_count();
        // Correct count, wrong fingerprint → must fail with a regenerate hint.
        let err = rt.check_topology(n, 0).expect_err("fingerprint mismatch");
        assert!(format!("{err:#}").contains("regenerate"));
        // Matching fingerprint passes.
        let (root, _) = wire_pipeline();
        let probe = Graph::new(
            vec![root],
            RunMode::HistoricalFrom(NanoTime::ZERO),
            RunFor::Cycles(1),
        );
        rt.check_topology(n, fingerprint(&probe)).unwrap();
    }

    #[test]
    fn wiring_cycle_is_an_error() {
        use std::cell::RefCell;

        struct SelfCycleNode {
            upstream: RefCell<Option<Rc<dyn Node>>>,
        }
        impl MutableNode for SelfCycleNode {
            fn cycle(&mut self, _state: &mut GraphState) -> anyhow::Result<bool> {
                Ok(false)
            }
            fn upstreams(&self) -> UpStreams {
                match &*self.upstream.borrow() {
                    Some(u) => UpStreams::new(vec![u.clone()], vec![]),
                    None => UpStreams::none(),
                }
            }
        }

        let node = Rc::new(RefCell::new(SelfCycleNode {
            upstream: RefCell::new(None),
        }));
        let dyn_node: Rc<dyn Node> = node.clone();
        node.borrow().upstream.replace(Some(dyn_node.clone()));

        let err = generate(vec![dyn_node.clone()], &CodegenOptions::default())
            .expect_err("wiring cycle must fail generation");
        assert!(format!("{err:#}").contains("cycle"));

        let err = StaticRuntime::new(
            vec![dyn_node],
            RunMode::HistoricalFrom(NanoTime::ZERO),
            RunFor::Cycles(1),
        )
        .err()
        .expect("wiring cycle must fail StaticRuntime::new");
        assert!(format!("{err:#}").contains("cycle"));
    }

    #[cfg(feature = "dynamic-graph")]
    #[test]
    fn dynamic_graph_changes_are_rejected() {
        struct DynamicAdder {
            upstream: Rc<dyn Node>,
        }
        impl MutableNode for DynamicAdder {
            fn cycle(&mut self, state: &mut GraphState) -> anyhow::Result<bool> {
                let extra = ticker(Duration::from_nanos(50));
                state.add_upstream(extra, true, false);
                Ok(true)
            }
            fn upstreams(&self) -> UpStreams {
                UpStreams::new(vec![self.upstream.clone()], vec![])
            }
        }

        let source = ticker(Duration::from_nanos(100));
        let node = DynamicAdder { upstream: source }.into_node();
        let err = drive_static(
            vec![node],
            RunMode::HistoricalFrom(NanoTime::ZERO),
            RunFor::Cycles(3),
        )
        .expect_err("dynamic additions must be rejected by the static runner");
        assert!(format!("{err:#}").contains("not supported"));
    }

    #[test]
    fn short_type_name_strips_generics() {
        assert_eq!("MapStream", short_type_name("MapStream<u64, bool>"));
        assert_eq!("TickNode", short_type_name("TickNode"));
    }
}
