name: Integration Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  kdb-integration:
    name: KDB Integration Tests
    uses: ./.github/workflows/kdb-integration.yml
    secrets: inherit

  etcd-integration:
    name: etcd Integration Tests
    uses: ./.github/workflows/etcd-integration.yml
    secrets: inherit

  telemetry-integration:
    name: Telemetry Integration Tests
    uses: ./.github/workflows/telemetry-integration.yml
    secrets: inherit

  otlp-integration:
    name: OTLP Integration Tests
    uses: ./.github/workflows/otlp-integration.yml
    secrets: inherit

  zmq-integration:
    name: ZMQ Integration Tests
    uses: ./.github/workflows/zmq-integration.yml
    secrets: inherit

  zmq-etcd-integration:
    name: ZMQ etcd Integration Tests
    uses: ./.github/workflows/zmq-etcd-integration.yml
    secrets: inherit
