name: Integration Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  kdb-integration:
    name: KDB Integration Tests
    uses: ./.github/workflows/kdb-integration.yml
    secrets: inherit

  etcd-integration:
    name: etcd Integration Tests
    uses: ./.github/workflows/etcd-integration.yml
    secrets: inherit
