name: Integration Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  adapter-integration:
    name: Adapter Integration Tests
    uses: ./.github/workflows/adapter-integration.yml
    secrets: inherit

  kdb-integration:
    name: KDB Integration Tests
    uses: ./.github/workflows/kdb-integration.yml
    secrets: inherit

  etcd-integration:
    name: etcd Integration Tests
    uses: ./.github/workflows/etcd-integration.yml
    secrets: inherit

  prometheus-integration:
    name: Prometheus Integration Tests
    uses: ./.github/workflows/prometheus-integration.yml
    secrets: inherit

  otlp-integration:
    name: OTLP Integration Tests
    uses: ./.github/workflows/otlp-integration.yml
    secrets: inherit

  zmq-etcd-integration:
    name: ZMQ etcd Integration Tests
    uses: ./.github/workflows/zmq-etcd-integration.yml
    secrets: inherit

  iceoryx2-integration:
    name: iceoryx2 Integration Tests
    uses: ./.github/workflows/iceoryx2-integration.yml
    secrets: inherit

  web-integration:
    name: Web Integration Tests
    uses: ./.github/workflows/web-integration.yml
    secrets: inherit

  kafka-python-integration:
    name: Kafka Python Integration Tests
    uses: ./.github/workflows/kafka-python-integration.yml
    secrets: inherit
